google/santa

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santactl/sync/SNTAuthenticatingURLSession.h
Source/santactl/sync/SNTAuthenticatingURLSession.m
Source/santactl/sync/SNTCommandSync.m

* improved logging
* exit with error when configuration file couldn't be opened
* removed hardcoded NO for using client certificates
* added support for pkcs#12 files
* fixed issue with ignoring client certificate configuration

Work on client certificates

---

Source/SantaGUI/SNTAppDelegate.m

Fix application deadlock by asynchronously dispatching to the main queue in -[SNTAppDelegate createConnection].

Fix application deadlock.

---

Source/common/SNTLogging.m

It is better to use fwrite as it is generally faster and we are not
using any fprintf feature

Using fwrite as we know the length of string

---

Source/common/SNTFileInfo.m

Minor optimization. Cache objc method call in local variable to avoid a
second call

Cache method call

---

Source/santad/SNTEventLog.m

Verified with lldb that that it is in fact a string copy

Avoid two string copies

---

Conf/uninstall.sh

leaves configs, performs no checks about current state but should be
relatively idempotent (can't unload/rm stuff that's not there). Thought this was more straightforward than an uninstall package.

add uninstall script

---

Source/santa-driver/SantaDriverClient.cc
Source/santa-driver/SantaDriverClient.h

SantaDriverClient was implemented to have static functions that call instance
methods passing appropriate arguments. While this works and is 'technically correct' (best kind),
it's a bit messy and hard to read.

santa-driver: Remove the static wrappers in SantaDriverClient

---

Source/common/SNTKernelCommon.h
Source/santa-driver/SantaDecisionManager.cc

Also force the likely/unlikely macros into boolean comparison and force the idata/sdm checks after casting.

santa-driver: Don't filter advisory vnode_write notifications

---

Source/common/SNTFileWatcher.m

I'm not certain if this is a Sierra change or just that it was more rare before but changing a cancel handler on a dispatch source no longer seems to have any effect. This meant the file descriptor for the currently-active source was being closed instead of the one for the source that was just cancelled. It wasn't actually necessary to get the file handle from the source, we can just rely on capturing it in the block, which works just as well.

santad: Update SNTFileWatcher to fix broken dispatch source.

---

Source/santad/SNTExecutionController.m

We only _really_ care about the signature on a binary and this errSecCSInfoPlistFailed error seems to pop-up with no discernible pattern or reason.

santad: Start ignoring errSecCSInfoPlistFailed (-67030)

---

Source/santad/SNTEventLog.m

While appendFormat with %s is slightly faster (~1üs) it doesn't handle UTF-8 properly and I can't figure out a better way than this (though I'm sure there is one)

santad: Handle UTF-8 in process args.

---

Source/santad/DataLayer/SNTRuleTable.m

Otherwise the required rule protection breaks.

santad: Handle case where there are multiple rules for req'd certs

---

Source/common/SNTConfigurator.m

NSString has longLongValue but not longValue, so switch to that then cast down. Check that the receiver responds to longLongValue before calling it just in case someone tries to set it to an NSData or something.
Fixes #102

Common: Don't crash if ClientMode key is not an integer.

---

Source/santa-driver/SantaDecisionManager.cc
Source/santa-driver/SantaDriverClient.cc

1. Don't RemoveFromCache for advisory access by santad itself.
2. wakeup sleeping threads when removing from cache
3. Move the vnode type check earlier in the process for the vnode scope

santa-driver: Fix deadlocking on Sierra

---

Source/santactl/Commands/SNTCommandFileInfo.m
Tests/LogicTests/SNTCommandFileInfoTest.m

*  https://github.com/google/santa/issues/112 Add missing pretty output check around the clear line escape sequence
*  Collapses all pretty output checks to a single function
*  Only run isatty() once saving some time

SNTCommandFileInfo global json bool shared between class and instance methods

---

Source/santactl/Commands/sync/SNTCommandSyncEventUpload.m
Tests/LogicTests/SNTCommandSyncTest.m

This speeds up bundle searching significantly, while limiting CPU use and maintaining a timeout for a single bundle. I've also added a test for the bundle searching code.

santactl/sync: Fix bundle searching, make concurrent.

---

Source/santactl/Commands/SNTCommandStatus.m

Fix for https://github.com/google/santa/issues/124

santactl status: check non-boxed vars when building json output

---

Source/santactl/Commands/SNTCommandFileInfo.m

santactl/fileinfo: Send resolved path to santad for processing

---

Source/santad/DataLayer/SNTEventTable.m

It isn't necessary and:
> imposes extra CPU, memory, disk space, and disk I/O

santad: Drop AUTOINCREMENT on event table

---

Santa.xcodeproj/project.pbxproj
Source/common/SNTStoredEvent.h
Source/common/SNTStoredEvent.m
Source/common/SNTXPCControlInterface.h
Source/common/SNTXPCSyncdInterface.h
Source/common/SNTXPCSyncdInterface.m
Source/santactl/Commands/sync/SNTCommandSync.m
Source/santactl/Commands/sync/SNTCommandSyncEventUpload.m
Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
Source/santad/DataLayer/SNTEventTable.h
Source/santad/DataLayer/SNTEventTable.m
Source/santad/SNTApplication.m
Source/santad/SNTDaemonControlController.h
Source/santad/SNTDaemonControlController.m
Source/santad/SNTExecutionController.h
Source/santad/SNTExecutionController.m
Source/santad/SNTSyncdQueue.h
Source/santad/SNTSyncdQueue.m
Tests/LogicTests/SNTEventTableTest.m
Tests/LogicTests/SNTExecutionControllerTest.m

-  New events are sent directly from santad --> santactl for immediate upload. No need to read from events.db for single event uploads. All events are still saved to events.db and those not uploaded immediately are uploaded during full syncs.
-  Continues to perform full syncs every 10 minutes. Only now this is scheduled and performed by santactl.
-  The event `idx` field in events.db is now randomly generated at event creation time instead of being set at regeneration time. This will allow santactl to remove events from events.db when it uploads a single event from santad.
-  First step in supporting FCM push notifications https://github.com/google/santa/issues/121

run santactl as a sync daemon

---

Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m
Source/santactl/Commands/sync/SNTCommandSyncState.h

*  Cache rule metadata contained in FCM message.
*  Search the cache when a rule is applied as a result of a FCM message and add the binary name to the user notification.

Display the binary name in rule sync user notifications

---

Source/santactl/Commands/sync/SNTCommandSyncConstants.h
Source/santactl/Commands/sync/SNTCommandSyncConstants.m
Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m
Source/santactl/Commands/sync/SNTCommandSyncState.h

*  Provides better assurance that a notification is mapped to the requesting machine.
*  Defaults to staggered rule downloads if machine ids do not match.

Use machine ids as the targeted sync indicator

---

Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m
Source/santad/SNTDaemonControlController.m

*  `santactl sync`: Retry failed full syncs once the url is reachable
*  `santactl sync`: rule_sync action messages contain a hash and the name of the binary rule generated for the machine. That data is cached and looked up later during the rule download phase. To avoid potentially displaying the wrong name for a current user action, I propose we display all downloaded rules names that can be found in the cache. We then remove each cached item as we go through the list. This will give more accurate feedback and mitigate laptops waking from sleep from displaying an older cached name in response to a current user action. If there are multiple rules generated while a machine is asleep, upon wake the notifications are grouped like so.
*  `santad`: Allow only one syncd connection at any given …

santactl sync: reachability and notification updates santad: syncd xpc updates

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/common/SNTXPCControlInterface.h
Source/santactl/Commands/SNTCommandStatus.m
Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m
Source/santad/SNTDaemonControlController.m

Note there is a change to the `santactl status --json` api under the `sync` key.
* Change `last_successful` --> `last_successful_full`
* Add `last_successful_rule`

santactl status: add last successful rule sync date

---

Source/santad/SNTDaemonControlController.m

When white/black-list regexes are changed clear the kernel cache so the regexes are able to take effect immediately. Fixes #142

santad: Clear cache when regexes change.

---

Podfile.lock
Santa.xcodeproj/project.pbxproj
Source/santactl/Commands/sync/SNTCommandSyncEventUpload.h
Source/santactl/Commands/sync/SNTCommandSyncEventUpload.m
Source/santactl/Commands/sync/SNTCommandSyncManager.m
Tests/LogicTests/SNTCommandSyncTest.m

*  santactl/sync: disable sync server bundle scan requests. This feature, as implemented, won't complete scans because santactl runs as `nobody`. Additionally there have been reports of strange santactl crashes with Foundation backtraces. I suspect because of the `nobody` user. Remove the code path. A full featured implementation will be in https://github.com/google/santa/pull/145.
*  config: update to cocoapods-1.2.0 and molfcmclient 1.2

disable bundle scans

---

Source/common/SNTXPCConnection.m
Source/santactl/Commands/SNTCommandCheckCache.m
Source/santactl/Commands/SNTCommandFileInfo.m
Source/santactl/Commands/SNTCommandFlushCache.m
Source/santactl/Commands/SNTCommandRule.m
Source/santactl/Commands/SNTCommandStatus.m
Source/santactl/Commands/SNTCommandVersion.m
Source/santactl/Commands/sync/SNTCommandSync.m
Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/SNTCommandController.h
Source/santactl/SNTCommandController.m

*  santactl/sync: use hostname for reachability of the sync service
*  Also revert #141 - this change provided little benefit and is actually less flexible

santactl/sync: use hostname for reachability

---

Source/common/SNTFileWatcher.m
Source/santactl/Commands/SNTCommandStatus.m

*  	https://github.com/google/santa/issues/151 common: capture fileSystemRepresentation as a local variable to avoid a leak in it's implementation
*  A big thanks to @LtMama for reporting this issue and providing memory graphs to track down the issue.
*  	santactl/status: check for instant notification status only when there is a sync server

Running without a config fixes

---

Podfile
Podfile.lock
Source/santactl/Commands/sync/SNTCommandSyncManager.m

*  MOLFCMClient has been updated in v1.3 to use fcm-stream
*  Handle the new message content of `foo:bar` instead of `{key:foo, value:bar}`

santactl/sync: use the new fcm-stream format

---

.gitignore
Podfile.lock
Rakefile
Santa.xcodeproj/project.pbxproj
Source/santa-driver/SantaCache.h
Source/santad/SNTDriverManager.m
Source/santad/main.m

This is a generated xcconfig in the Rakefile which gets included by the project
to set the DEVELOPMENT_TEAM key to keep Xcode 8 happy. The development team is
figured based on the available “Mac Developer” certificate.
Also update the way SantaCache declares a ‘zero’ value, update the
OCMock and MOLAuthenticatingURLSession pods and add a few missing includes.

Project: Add DevelopmentTeam configuration

---

Source/santa-driver/SantaCache.h

Initializing T with 0 when T is `std::string` crashes. We don't use SantaCache with strings in any of the production code, but there is a test that does. The default initialization for `uint64_t` and `std::string` seems to work fine.
Alternatively we can remove the test and update the wording in SantaCache to only support int style types.

SantaCache fix 0 init

---

Source/santactl/Commands/sync/SNTCommandSyncEventUpload.m

The `bundleBinaryRequests` property holds an array of bundle hashes for a given sync session. These hashes represent a fulfillment request from the sync server. If the client has the corresponding bundle hash and released events, it will begin uploading them.

Update bundleBinaryRequests on Event Upload

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/common/SNTXPCControlInterface.h
Source/common/SNTXPCSyncdInterface.h
Source/santactl/Commands/sync/SNTCommandSync.m
Source/santactl/Commands/sync/SNTCommandSyncConstants.h
Source/santactl/Commands/sync/SNTCommandSyncConstants.m
Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/Commands/sync/SNTCommandSyncPostflight.m
Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
Source/santactl/Commands/sync/SNTCommandSyncState.h
Source/santad/SNTDaemonControlController.m

*  Handle `fcm_full_sync_interval` and `fcm_global_rule_deadline` values during preflight
*  If there is no SyncBaseURL exit
*  Remove support for `backoff`

santactl/sync: Sync Server to set FCM interval and deadline

---

Source/SantaGUI/Resources/MessageWindow.xib
Source/SantaGUI/SNTMessageWindowController.m
Source/SantaGUI/SNTNotificationManager.m
Source/common/SNTConfigurator.h
Source/common/SNTStoredEvent.h
Source/common/SNTStoredEvent.m
Source/common/SNTXPCControlInterface.h
Source/santactl/Commands/SNTCommandStatus.m
Source/santactl/Commands/sync/SNTCommandSyncConstants.h
Source/santactl/Commands/sync/SNTCommandSyncConstants.m
Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
Source/santad/SNTDaemonControlController.m
Source/santad/SNTExecutionController.m

This pull is branched from https://github.com/google/santa/pull/168, ensure that 168 has been submitted before processing this request. I am mainly doing this now as to not forget.
*  santactl/sync: sync server enables/disables client bundle support

make bundle support configurable from a sync server

---

Source/common/SNTXPCControlInterface.h
Source/santactl/Commands/SNTCommandFileInfo.m
Source/santactl/Commands/SNTCommandRule.m
Source/santad/SNTDaemonControlController.m
Source/santad/SNTExecutionController.m
Source/santad/SNTPolicyProcessor.h
Source/santad/SNTPolicyProcessor.m

Add the ability to check the status of arbitrary sha256 hashes without on-disk artifacts. This duplicates some pretty printing code from fileinfo. At some point we should make a class to handle santactl output.
Example:
Check the status of the`/usr/bin/yes` binary.
```
sudo santactl rule --check --sha256 e8e3e5700e9e023d09aa85f0dbd7f2f53e83bcd6f7380edbf9666e7f470f0c50
Blacklisted (Binary)
```
Check the status of the Apple Software Signing certificate.
```
sudo santactl rule --check --certificate --sha256 2aa4b9973b7ba07add447ee4da8b5337c3ee2c3a991911e80e7282e8a751fc32
Whitelisted (Certificate)
```

santactl/rule: add --check flag

---

Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m

The FCM notifications include both file_name and file_hash keys but in
some cases file_name is actually a 0-length string. Regardless, checking
an NSString's length property is the best way to check for both nil and
0 length so let's just do that.

SantaGUI: Don't show pop-up notifications for empty filenames

---

Source/SantaGUI/SNTNotificationManager.m
Source/common/SNTStoredEvent.h
Source/common/SNTStoredEvent.m
Source/santabs/SNTBundleService.m
Source/santactl/Commands/sync/SNTCommandSyncConstants.h
Source/santactl/Commands/sync/SNTCommandSyncConstants.m
Source/santactl/Commands/sync/SNTCommandSyncEventUpload.m

Do this for bundle events to allow a sync-server to determine the main executable.

santactl/sync: upload file bundle executable relative path

---

Source/common/SNTXPCConnection.m

I've added a comment explaining in what circumstance this can happen, it's unusual.

SNTXPCConnection: Prevent crash if caller releases during resume

---

Source/common/SNTBlockMessage.m
Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m

The changes to bundle scanning mean this key isn't really necessary anymore - if a server supports bundles it tells the client during preflight, this in turn causes bundle hashes to be generated and these are used in place of the file hash when generating a detail URL. Keying bundles off the ID and version was never really a good idea anyway.

common: Remove EventDetailBundleURL key

---

Source/santad/SNTEventLog.m

Fixed problem where extremely long path/args obscured other log info.

santad: modified execution log format to show path & args at end

---

Source/common/SNTFileInfo.m
Source/common/SNTLogging.h
Source/common/SNTXPCControlInterface.h
Source/santa-driver/SantaDecisionManager.cc
Source/santa-driver/SantaDecisionManager.h
Source/santa-driver/SantaDriverClient.cc
Source/santactl/Commands/SNTCommandStatus.m
Source/santad/SNTApplication.m
Source/santad/SNTDaemonControlController.m
Source/santad/SNTDriverManager.h
Source/santad/SNTDriverManager.m
Source/santad/SNTEventLog.m
Tests/KernelTests/main.mm

Split the kernel cache into 2 separate caches, one for the root volume and one for secondary volumes. When an unmount happens, clear the non-root cache to ensure no overlap with filesystem IDs. Show the count for both caches in the santactl/status command.
Reduce the total cache size from **10k** entries to **5k (root) + 500 (non-root)**.
Also attempt to make logging slightly less bad in the kernel, using a gcc/clang varargs extension to avoid needing to call IOLog twice per output line.

Split kernel cache for root/non-root volume.

---

Source/santa-driver/SantaCache.h
Source/santa-driver/SantaDecisionManager.cc
Tests/KernelTests/main.mm
Tests/LogicTests/SantaCacheTest.mm

SantaDecisionManager::AddToCache() rejects allow/deny entries being added to the
cache unless there's already an entry for that vnode with the REQUEST_BINARY
status, so that if a write to the file happens and the entry is removed while a
decision is being made, it's rejected.
However, as it's currently implemented there's a small window where the entry is
actually added to the cache. To fix that, this PR adds a way to use the
cache->set() method as a compare-and-swap.
While here, I also fixed the cache performance test in KernelTests so that it
measures walltime instead of CPU time.
Also fixed some line length violations.

santa-driver: Fix possible race condition in SDM::AddToCache

---

Source/santad/SNTEventLog.m

Currently using "origpath" as key in logged output for the original path of the translocated binary; may want to change to something else.

santad/SNTEventLog: log original path of translocated apps

---

Santa.xcodeproj/project.pbxproj
Source/common/SNTFileInfo.h
Source/common/SNTFileInfo.m
Source/santabs/SNTBundleService.m
Source/santactl/Commands/SNTCommandBundleInfo.m
Source/santactl/Commands/SNTCommandCheckCache.m
Source/santactl/Commands/SNTCommandFileInfo.m
Source/santactl/Commands/SNTCommandFlushCache.m
Source/santactl/Commands/SNTCommandRule.m
Source/santactl/Commands/SNTCommandStatus.m
Source/santactl/Commands/SNTCommandVersion.m
Source/santactl/Commands/sync/SNTCommandSync.m
Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/SNTCommand.h
Source/santactl/SNTCommand.m
Source/santactl/SNTCommandController.h
Source/santactl/SNTCommandController.m
Tests/LogicTests/SNTCommandFileInfoTest.m
Tests/LogicTests/SNTEventTableTest.m

Sorry this is so large.  This implements the recursive fileinfo command and adds the ability to specify multiple --key flags.  I haven't implemented filtering yet, because it seemed like it was already too much change at once.
I rewrote the SNTCommand* classes so that they would behave more consistently.  They all inherit from SNTCommand and now all instantiate themselves in the same way before running, which means they all run as instances instead of some commands being implemented entirely with class methods.

santactl: Recursive fileinfo command

---

Source/common/SNTXPCSyncdInterface.h
Source/common/SNTXPCSyncdInterface.m
Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santad/SNTDaemonControlController.m
Source/santad/SNTExecutionController.m
Source/santad/SNTSyncdQueue.h
Source/santad/SNTSyncdQueue.m

* SNTSyncdQueue addBundleEvents: and addEvent: became addEvents:isFromBundle:
* SNTSyncdQueue backoffForBundleHash: and backoffForEvent: became backoffForPrimaryHash:
* SNTCommandSyncManager postBundleEventsToSyncServer: and postEventToSyncServer: became postEventsToSyncServer:isFromBundle:

Minor refactor to merge similar methods into one:

---

Source/santad/SNTExecutionController.m

It is too broad a check for the few false positive events we have seen.

santad: Stop ignoring CSInfoPlistFailed

---

Source/santad/SNTPolicyProcessor.m

Fixes `santactl rule --check` returning `Whitelisted (Scope)` incorrectly

santad: SNTPolicyProcessor fix nil scope check

---

Source/santactl/main.m

Fixes #216 .  As implemented -h and --help must be the first argument to do anything which I think is sort of reasonable as there is an extremely remote possibility that have a file named "--help" that you wanted to run fileinfo on.

santactl: Added -h and --help as synonyms for help

---

Source/SantaGUI/SNTAppDelegate.m
Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santad/SNTApplication.m
Source/santad/SNTDaemonControlController.m

*  `/var/db/santa/config.plist` is now ignored and not used
*  `/var/db/santa/sync-state.plist` now holds state from the sync server
*  `com.google.santa` mobileconfig is now used for configuration
*  If a mobileconfig manages the `SyncBaseURL` the ` kClientModeKey` `kWhitelistRegexKey` `kBlacklistRegexKey` `kFileChangesRegexKey` keys will be ignored within the mobile config.
Fixes https://github.com/google/santa/issues/209
~~One note: The sync-state.plist could include values from a mobile config if the sync server is not setting them. This "effective" sync-state will only make a difference if the mobile config changed values while santad was not running and the sync server was not managing those values.~~

SNTConfigurator: use mobileconfigs

---

Santa.xcodeproj/project.pbxproj
Source/SantaGUI/SNTAppDelegate.m
Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/common/SNTXPCControlInterface.h
Source/santactl/Commands/SNTCommandStatus.m
Source/santactl/Commands/sync/SNTCommandSyncPostflight.m
Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
Source/santad/SNTApplication.m
Source/santad/SNTDaemonControlController.m

Whenever there is a system wide mobileconfig change, all on-disk representations are deleted and re-created...twice (Thanks Apple). This flapping causes Santa to reload its config many times over a short period of time. In some cases this can result in an incorrect running config.
*  Build and merge the new config in temporary variables.
*  Let the caller of `reloadConfigData` know if a reload is taking place.
*  Update callers to not do unnecessary work.

 config: use KVO

---

Podfile.lock
Source/santactl/Commands/SNTCommandFileInfo.m

*  Use pod MOLCodesignChecker v1.8 - this includes the use of the kSecCSCheckAllArchitectures flag for code signature verification.
*  `santactl fileinfo` now displays the correct `Rule` for binaries that are signed but invalid.

codesign check: verify all architectures

---

Source/santabs/SNTBundleService.m

Prevent possible "XPC API Misuse: Over-resume of a connection"

santabs: Serialize calls to -[SNTBundleService createConnection]

---

Source/santad/SNTApplication.m

* If the SyncBaseURL disappears, keep the syncState active for 5 seconds before clearing.

sync-state: Mitigate com.apple.ManagedClient flapping

---

Podfile.lock
Source/common/SNTFileInfo.h
Source/common/SNTFileInfo.m
Source/santactl/Commands/SNTCommandFileInfo.m
Source/santad/SNTExecutionController.m
Tests/LogicTests/SNTExecutionControllerTest.m

* Use MOLCodesignChecker v1.10
* Update `santactl fileinfo` to display universal signing information when appropriate

santad / santactl: validate all architectures within universal binaries

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santad/Logs/SNTEventLog.h
Source/santad/Logs/SNTEventLog.m
Source/santad/Logs/SNTSyslogEventLog.m

The way we aggregate logs means it can be hard to tell where they are coming from when they get to our backend. This PR adds a new ~`UUID`~ `machineid` field to logs if ~EnableUUIDDecoration~ EnableMachineIDDecoration is set.
~I'm still working on testing this with a configuration profile and will update when I confirm it works the way I expect.~
This is also planned to be contributed on behalf of @Facebook so I've also started an internal authorization for CLA signing.
**Testing:**
Here is a snippet of the mobileconfig I installed locally on my machine:
```
<key>EnableMachineIDDecoration</key>
<integer>1</integer>
```
I confirmed that logs get have:
```
|machineid=XXX...XXX
```
appended to them and when I reinstall the profile with a 0 the field is no longer present.

Optional MachineID for Logs

---

Source/santa-driver/SantaCache.h
Source/santa-driver/SantaDecisionManager.cc
Source/santa-driver/SantaDecisionManager.h

Also re-order some of the public functions in SantaCache and move the initialization of the ts_ struct in SDM into the header.

santa-driver: Fix cache CAS operations, which haven't been working

---

Santa.xcodeproj/project.pbxproj
Source/common/SNTKernelCommon.h
Source/common/SNTXPCControlInterface.h
Source/santa-driver/SantaDecisionManager.cc
Source/santa-driver/SantaDecisionManager.h
Source/santa-driver/SantaDriverClient.cc
Source/santa-driver/SantaDriverClient.h
Source/santactl/Commands/SNTCommandBundleInfo.m
Source/santactl/Commands/SNTCommandCacheHistogram.m
Source/santactl/Commands/SNTCommandCheckCache.m
Source/santad/SNTDaemonControlController.m
Source/santad/SNTDriverManager.h
Source/santad/SNTDriverManager.m

The command only exists in Debug builds.
This currently only prints the distribution of the non-root cache. In the near future I'll unify the caches again which stops this being a problem.

SantaCache: Add command to print histogram of bucket distribution

---

Source/santa-driver/SantaDecisionManager.cc
Source/santa-driver/SantaDriverClient.cc
Source/santa-driver/SantaDriverClient.h

This fixes IOServiceClose() being called on the driver
Also don't delete and re-enqueue the log data queue if it fails to enqueue, this is pointless.

santa-driver: Re-factor some destruction methods

---

Rakefile
Santa.xcodeproj/xcshareddata/xcschemes/KernelTests.xcscheme
Source/santa-driver/SantaDriverClient.cc
Source/santa-driver/SantaDriverClient.h
Tests/KernelTests/main.mm

This change does 2 major things:
1) Makes the test runnable from within Xcode, unloading any running
santad and santa-driver, loading the just-built driver from the same folder and
then running each test.
2) Makes each test responsible for declaring what should happen to
incoming requests from the driver, instead of keeping all of that
code near the top of the file. This makes each test much clearer in what
should be happening.

KernelTests: Simplify kernel tests

---

Source/santa-driver/Resources/santa-driver-Info.plist

It seems this was not needed <= 10.13, but 10.14 will not match on IOResources alone.

santa-driver: add IOMatchCategory

---

Podfile.lock
Source/santad/DataLayer/SNTRuleTable.h
Source/santad/DataLayer/SNTRuleTable.m
Source/santad/SNTExecutionController.m

* In Mojave `/usr/libexec/trustd` needs to run in order to check arbitrary code signatures. This may be a departure from previous version of macOS. If `trustd` is killed, Santa can cause a deadlock. This fix pre-validates and whitelists `trustd` at `santad` startup time.
* Fixes #295

santad: add critical system binaries

---

Source/santad/DataLayer/SNTRuleTable.m

* Adding the`kSecCSNoNetworkAccess` flag to MOLCodesignChecker has no effect 😢

ocspd also seems integral to cs validation

---

Source/common/SNTXPCUnprivilegedControlInterface.h
Source/santa-driver/SantaDecisionManager.cc
Source/santa-driver/SantaDecisionManager.h
Source/santa-driver/SantaDriverClient.cc
Source/santactl/Commands/SNTCommandCacheHistogram.m
Source/santactl/Commands/SNTCommandStatus.m
Source/santad/SNTApplication.m
Source/santad/SNTDaemonControlController.m
Source/santad/SNTDriverManager.h
Source/santad/SNTDriverManager.m
Tests/KernelTests/main.mm

* santa-driver now supports 64 bit file system ids. Identifying root and non-root file system ids on executing binaries seems to now work consistently.
* Clarify buckets and entries in non-graphical cachehistogram output.
This pull is mainly a line by line cherrypick revert of 15fa53d744368752ff1b55dcbdd62020e060c629.

santa-driver: add back the root and non-root caches

---

Docs/deployment/configuration.md

- SyncBaseURL is not overridable by the server.
- ATS requires a self signed certificate to exist in the system roots. Providing roots enables in the Santa configuration enables pinning.
Closes #309

update deployment documentation

---

Santa.xcodeproj/project.pbxproj
Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/common/SNTKernelCommon.h
Source/santa-driver/SantaDecisionManager.cc
Source/santa-driver/SantaDecisionManager.h
Source/santa-driver/SantaDriverClient.cc
Source/santa-driver/SantaDriverClient.h
Source/santa-driver/SantaPrefixTree.cc
Source/santa-driver/SantaPrefixTree.h
Source/santad/SNTApplication.m
Source/santad/SNTDriverManager.h
Source/santad/SNTDriverManager.m
Tests/KernelTests/main.mm

* Allow santa-driver to ignore file changes with a prefix filter.
* Stops unnecessary generation of events that would be ignored by santad with a regex or lack of one.
* Prefixes are configurable with the mobileconfig.

add in-kernel filemod prefix filter

---

Source/santa-driver/SantaDecisionManager.cc
Tests/LogicTests/SNTCommandFileInfoTest.m
Tests/LogicTests/SNTRuleTableTest.m

* remove vnode_pid_map: It is only used for logging execs. Creating a new message will get the executing PID and PPID.
* fix logic tests under Xcode 10.1

document vnode_pid_map

---

.travis.yml
BUILD
Docs/development/building.md
README.md
mkdocs.yml

I also made it so the santactl compilation won't include debug-only commands in release builds and the release rule will fail on a non-opt build.

Project: Update docs for switch to bazel

---

Source/santad/Logs/SNTSyslogEventLog.m

They were lost in the refactoring of the logging utility 4a2cf9d722a4e2d88f6b0b560ddee44706ea4442.

resurrect action=BUNDLE logs

---

Source/SantaGUI/BUILD
Source/SantaGUI/Resources/AboutWindow.xib
Source/SantaGUI/Resources/MessageWindow.xib
Source/common/BUILD
Source/common/SNTBlockMessage.m

* Note:  I left the `@media (prefers-color-scheme: dark)` check. When the shipping WebKit supports the call, it may updated the UI? For now it is a NOP.

SantaGUI: Fix message text. Add support for Dark Mode.

---

Source/santa_driver/BUILD

* Allows a userland version of SantaPrefixTree to be used by future rules.

tests: Create a SantaPrefixTree userland lib

---

.bazelrc
.travis.yml
WORKSPACE

* bazel 0.27.0 defaults to python 3 - added a flag to .bazelrc to force python 2

Use updated deps

---

Source/SantaGUI/SNTNotificationManager.m

When setting a new bundle service listener, it was possible for an existing listener to be replaced without invalidating it first. This can cause crashes if a process somehow tries to connect to that listener later on.

SantaGUI: ensure bundle listeners are invalidated

---

Source/santad/DataLayer/SNTRuleTable.m

dyld is also authorized by santad and a bad cache eviction plus trustd/ocspd not running can result in deadlock.
Fixes #375, probably.

santad: Add /usr/lib/dyld to critical system binaries

---

Conf/com.google.santa.bundleservice.plist
Santa.xcodeproj/project.pbxproj
Source/common/BUILD
Source/common/SNTXPCBundleServiceInterface.h
Source/common/SNTXPCBundleServiceInterface.m
Source/common/SNTXPCNotifierInterface.h
Source/common/SNTXPCNotifierInterface.m
Source/common/SNTXPCUnprivilegedControlInterface.h
Source/common/SNTXPCUnprivilegedControlInterface.m
Source/santa/SNTAppDelegate.m
Source/santa/SNTNotificationManager.h
Source/santa/SNTNotificationManager.m
Source/santabundleservice/SNTBundleService.m
Source/santabundleservice/main.m
Source/santactl/Commands/SNTCommandBundleInfo.m
Source/santad/SNTDaemonControlController.m

* santabundleservice and Santa.app now talk directly without any proxying by santad.
* santabundleservice now runs on-demand.

simplify santabundleservice xpc connection protocol

---

Source/santad/EventProviders/SNTEndpointSecurityManager.mm

* For large binaries, ACTION_RESPOND_ACK was double freeing the es message.
* Don't apply the prefix filter to exec events.

handle all ACTION_RESPOND_*

---

Source/common/BUILD
Source/santa_driver/main.cc

Missed this pulling into master before.

santa-driver: Workaround 10.15 SDK Dispatch() issue

---

WORKSPACE

This version is compatible with bazel 2.0, which is what Travis is using.

Project: update Apple rules to 0.19.0

---

Source/santactl/Commands/sync/SNTCommandSyncEventUpload.m

This lets a clean sync clear out the existing events without attempting to upload them.

santactl/sync: Skip event upload for clean sync

---

Source/common/SNTCachedDecision.h
Source/santad/EventProviders/SNTEndpointSecurityManager.mm
Source/santad/SNTDaemonControlController.m
Source/santad/SNTExecutionController.m
Source/santad/SNTExecutionControllerTest.m
Source/santad/SNTPolicyProcessor.h
Source/santad/SNTPolicyProcessor.m

This also removes an unnecessary hash and checks code signatures on non-MachO files (which is rare but possible).
It also fixes a rare crash in EndpointSecurityManager

santad: Move signature fetching into SNTPolicyProcessor

---

Santa.xcodeproj/project.pbxproj
Source/common/SNTConfigurator.m
Source/santactl/Commands/sync/SNTCommandSync.m
version.bzl

* We were unintentionally watching for config changes in santactl, which causes issues getting an accurate config on boot. Fixed this by checking the process name before starting KVO.
* The sync command has been updated to require a connection to the daemon.

santactl: don't watch for config changes

---

Source/santa/SNTAppDelegate.m

* SystemExtension loading is handled by the .pkg or install.sh.
* Once loaded macOS makes sure it is always running, there is no need for Santa.app to keep asking.
* Asking to load the SystemExtension in quick succession seems to confuse macOS, in some cases causing it to ignore the MDM SystemExtension whitelist 🤷‍♂

Santa.app: don't request SystemExtension loading

---

docs/deployment/configuration.md

%bundle_id% and %bundle_ver% are not replaced any more, they were removed by https://github.com/google/santa/commit/6f417a17756ca794e3b7fc4ab6f0dccd431c1759#diff-3250262f27ab2cb96ad4b47abdc9d51fL95-L108

Remove %bundle_id% and %bundle_ver% from EventDetailURL docs

---

docs/deployment/system-extension-policy.santa.example.mobileconfig
docs/deployment/tcc.configuration-profile-policy.santa.example.mobileconfig

Since the release of https://github.com/google/santa/releases/tag/1.0.3 Santa now requires additional SystemExtension and TCC permissions in order to run on 10.15+.
It took me a better part of a day to figure out the correct profile structure for each. So, I wanted to contribute some examples for future admins to reference.
These configurations are working in my deployment. I don't receive a System Extension prompt upon install nor do I receive a TCC related prompt for `com.google.santa.daemon.systemextension`.
Output of `santactl status`:
```
santactl status
>>> Daemon Info
Driver Connected          | Yes
Mode                      | Monitor
File Logging              | No
Watchdog CPU Events       | 1  (Peak: 34.22%)
Watchdog RAM Events       | 0  (Peak: 41.33MB)
>>> Database Info
Binary …
```

Add example System Extension and TCC configuration profiles

---

Source/common/SNTBlockMessage.m
Source/common/SNTConfigurator.h
docs/deployment/configuration.md

Hello,
I've added support for `%hostname%`, `%uuid%` and `%serial%` to eventDetailURLForEvent to provide additional system information for blocked events. We're using the `%machine_id%` as our own unique identifier and it'd be useful to be able to provide some additional system information in event detail URLs for external systems that don't have access to the machine_id. 
Thanks
Best,
H

Support for %hostname%, %uuid% and %serial% to eventDetailURLForEvent

---

Source/santactl/Commands/sync/SNTCommandSyncConstants.h
Source/santactl/Commands/sync/SNTCommandSyncConstants.m
Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
Source/santactl/Commands/sync/SNTCommandSyncState.h
docs/deployment/configuration.md

Hello,
The documentation seems to suggest the ability to remotely set the default sync interval from 10 minutes. Though maybe this was only explicitly meant for FCM notifications? Either way, I'd like to be able to remotely set the sync interval for non-FCM driven deployments. Happy to discuss if was done for a specific design rationale. However, I'd like to be able to set the sync interval remotely based on different client groups.
If you're happy I'll add a follow on commit with updates to the docs.
Many thanks,
H

Make it possible to remotely set the FullSyncInterval

---

Source/santa_driver/BUILD
Source/santa_driver/SantaDecisionManager.cc

The `ossharedptr-misuse` warning is generated from within system headers and I couldn't find a simple way to prevent that other than disabling the warning entirely. We don't use `OSSharedPtr` directly anyway.

santa-driver: Fix some new Xcode 12 warnings

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/Commands/sync/SNTCommandSyncStage.m
Source/santactl/Commands/sync/SNTCommandSyncState.h
version.bzl

santactl sync: add config option to enable legacy zlib content encoding

---

Source/santactl/Commands/sync/SNTCommandSyncManager.m
Source/santactl/Commands/sync/SNTCommandSyncStage.m

Each request is retried up to 3 times with gaps of 2s, 4s, 6s

santactl/sync: retry individual requests during a sync

---

docs/deployment/notificationsettings.santa.example.mobileconfig

This is an example configuration profile to enable the Notifications settings for Santa. Notifications will be displayed in Apple Notification Center. Ideally this mobileconfig is deployed via MDM.

add .mobilecofig profile to enable Notifications settings for Santa

---

Source/common/SNTFileInfo.m

fileinfo: Don't use non-bundle dirs as possible ancestors

---

Source/common/SNTLogging.m
Source/santad/EventProviders/SNTCachingEndpointSecurityManager.mm
Source/santad/EventProviders/SNTEndpointSecurityManager.h
Source/santad/EventProviders/SNTEndpointSecurityManager.mm
version.bzl

There are a few related changes - the increase of the deadline timeout is because 2s seems just a fraction too short sometimes and adjusting the DEBUG log mapping was just to help debugging of this feature.
Fixes #539

santad: Fix transitive rules when using the sysx cache feature

---

BUILD
WORKSPACE
version.bzl

The reload command would previously fail if you used multiple compilation modes for building as it would try extracting the versions from both comp modes.
The dependency bump includes a fix for #553.
Bump Santa version to 2021.5

Project: Bump dependency versions, fix reload command

---

coverage/generate_cov.sh

Setting LCOV_MERGER (as done in https://github.com/bazelbuild/rules_apple/issues/338#issuecomment-620705204) results in `blaze coverage` of a test_suite collecting the test coverage of one test in the suite (presumably, the slowest test to complete). We can fix this by calling `blaze coverage` of all tests and then merging them afterwards.
We also want to avoid getting coverage of non-Santa binaries packaged in runfiles as testdata.

Fix coverage calculation by calling `blaze coverage` individually

---

BUILD
Source/santad/EventProviders/EndpointSecurityTestUtil.h
Source/santad/EventProviders/EndpointSecurityTestUtil.mm
Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm
coverage/generate_cov.sh

This enables the SNTEndpointSecurityManagerTest for our CI (having forgotten to do that in the initial PR) and (1) adds es_unsubscribe and es_delete_client to our ESF shim to fix the test segfaulting, and (2) cleans up the unit tests themselves by breaking out the timeout test from the regular unlink test

Include SNTEndpointSecurityManagerTest in the main test_suite 

---

.github/workflows/ci.yml

Especially due to https://github.com/actions/virtual-environments/issues/3885, a full build of the driver takes several minutes. Switch our CI steps to run our unit tests first, which are more likely to fail those build stages anyways.

Run Unit Tests & Coverage in CI first

---

Source/santad/EventProviders/SNTEndpointSecurityManager.mm
Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm

SNTEndpointSecurityManager checks the source of an es_event_rename_t for tampering with the santa databases (events.db and rules.db) but it doesn't check destinations. A user can arbitrarily overwrite either Santa database by renaming a file into the databases to remove/modify rules and events.

Prevent Overwrite of Santa Databases

---

.bazelrc
Source/common/SNTPrefixTree.cc
Source/common/SantaCache.h
Source/santad/EventProviders/EndpointSecurityTestUtil.h
Source/santad/EventProviders/EndpointSecurityTestUtil.mm
Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm
Source/santad/SNTApplicationTest.m

This PR enables -Werror -Wall on our build rules and fixes the following warnings:
*  Corrected signed/unsigned int conversions in SNTPrefixTree and Santacache
*  Nullability annotations to the rest of EndpointSecurityTestUtil
*  Reorder init lists in SNTEndpointSecurityManagerTest and SNTApplicationTest
*  Add annotations for "unused" (actually used) variables in SNTEndpointSecurityManagerTest
This should bring us in-line with internal warnings.

Enable -Werror -Wall on our build rules

---

Source/santad/EventProviders/SNTEndpointSecurityManager.mm
Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm

Santa times out on AUTH_RENAME of benign paths because we forgot to return an ES auth decision. This was also missed by the test coverage, so this PR also adds test coverage for handling and correctly caching benign paths.

Add missing ES Auth response to AUTH_RENAME

---

.bazelrc

We still want to see deprecated declaration warnings but they shouldn't cause builds to fail as often it's not possible to migrate immediately.

Project: remove py2 forcing, drop deprecation warnings back to warning

---

docs/_config.yml
docs/deployment/configuration.md
docs/deployment/index.md
docs/details/events.md
docs/details/index.md
docs/details/ipc.md
docs/details/logs.md
docs/details/mode.md
docs/details/rules.md
docs/details/santa-driver.md
docs/details/santa-gui.md
docs/details/santabs.md
docs/details/santactl.md
docs/details/santad.md
docs/details/scopes.md
docs/development/building.md
docs/development/contributing.md
docs/development/index.md
docs/index.md
docs/introduction/binary-authorization-overview.md
docs/introduction/index.md
docs/introduction/syncing-overview.md
docs/theme/Santa.css

This is the first step to fully deprecating the ReadTheDocs docs. There's still a lot of info in the docs that is outdated or could be much improved, which will come soon.

Docs: Switch themes, update config, fix redirect, update a couple things

---

WORKSPACE

Prior to https://github.com/bazelbuild/rules_apple/pull/1191, the macOS test runner's architecture is hardcoded to x86_64. This should let us run unit tests on M1 macs.

Upgrade bazel_rules_apple to 0.31.3

---

WORKSPACE

Turns out 3.13.3 doesn't actually include this commit. 
Tested locally on an M1 mac this time.

Pin bazel rules_apple to https://github.com/bazelbuild/rules_apple/pull/1191

---

.github/workflows/ci.yml

This changes the CI workflow steps to execute conditionally meaning that modifying
documentation we won't run the build, test and coverage steps.

Make CI build and test steps conditional

---

.github/workflows/ci.yml

Build and test steps were taking more than 5 minutes to run so this cleans up
the workflow and parallelizes it. 
It splits the workflow into the following 5 jobs.
| Job Name | Depends on | What does it do? |
|---|---|---|
| preqs | N/A | Checks which files were modified in the PR and sets outputs for conditional execution of later jobs. |
| build_userspace | preqs | Ensures that any changes still result in a working build |
| build_driver | preqs | Ensures that any changes to the driver still build |
| unit_tests | preqs | Runs all unit tests |
| test_coverage | preqs | Runs all tests for coverage and uploads to Coveralls |
preqs, build_userspace, build_driver, unit_tests, and test_coverage.  The last four jobs depend on preqs.

Rewrote ci.yml workflow to parallelize steps

---

Source/santa/BUILD
Source/santad/BUILD
Source/santad/com.google.santa.daemon.systemextension.entitlements

The build of Santa generated by --SANTA_BUILD_TYPE=ci currently can't actually get loaded, since the build doesn't include either of the entitlements we need. Internally, we inadvertently avoid this entire problem because the Santa provisionprofile includes the appropriate entitlements.

Add entitlements to the santad and Santa build rules

---

Source/santad/com.google.santa.daemon.systemextension.entitlements

The TeamIdentifierPrefix is required, but bazel fails to fill in `$(TeamIdentifierPrefix)` when using the `entitlements` parameter in a rule. 
We can just avoid this problem by explicitly filling it in instead.

Explicitly include the TeamIdentifierPrefix to santad's entitlement

---

README.md

We no longer have open positions, and the link should stop working.

Remove the hiring banner

---

.gitignore
Source/santa/BUILD
Source/santactl/BUILD
Source/santad/BUILD
Source/santad/com.google.santa.daemon.systemextension.entitlements
Testing/build_and_sign.sh
Testing/com.google.santa.mobileconfig
Testing/global.toml
Testing/init_dev_certs.sh
Testing/openssl.cnf
Testing/reset.sh
Testing/start_env.sh

This PR includes several scripts for building and setting up an integration test environment that doesn't require the Santa provisionprofile. This sets up an environment such that a build of santad with `--define=SANTA_BUILD_TYPE=ci` can actually load. 
I also tested whether the entitlements file change for santad affects our internal provisionfile - the entitlements in Santa_Daemon_Dev.provisionprofile will take priority over the `entitlements` build rule.

Include an integration test setup and fixture with moroz

---

Source/common/BUILD
Source/common/SNTXPCMetricServiceInterface.h
Source/common/SNTXPCMetricServiceInterface.m

Added an XPC interface for the SNTMetric Service this follows the internal design doc.
The protocol for the service adds a single method `- (void)exportForMonitoring:(NSDictionary *)metrics;` The metrics dictionary is expected to be exported from the SNTMetricSet.
This is a first in a series of related PRs.

Added an XPC interface for the Metric Service

---

Source/common/SNTCommonEnums.h
Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
docs/deployment/configuration.md

This PR adds the initial configuration options for the bare bones.
Specifically it adds the following three things:
| Option | Meaning |
|---|---|
| **MetricFormat** |  a string describing how metrics should be formatted. Supported options ("raw json" for a single JSON object containing all metrics, "json" for JSON metrics one metric per line.  |
|  **MetricURL** | a string URL describing  where to export the formatted metrics. |
| **exportMetrics** | a helper function in SNTConfigurator that checks if all necessary keys are set and metrics should be exported. | 
Part of #563.

Add initial configuration options for barebones metric service

---

Source/santad/EventProviders/EndpointSecurityTestUtil.h
Source/santad/EventProviders/EndpointSecurityTestUtil.mm
Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm
Source/santad/SNTApplicationTest.m

I found myself copy-pasting the same boilerplate everywhere while writing other tests. Upstreaming this first before writing more.

Create block builder for ES Messages and clean up tests

---

Source/santametricservice/BUILD
Source/santametricservice/Formats/BUILD
Source/santametricservice/Formats/SNTMetricFormatTestHelper.h
Source/santametricservice/Formats/SNTMetricFormatTestHelper.m
Source/santametricservice/Formats/SNTMetricRawJSONFormatTest.m
Source/santametricservice/SNTMetricServiceTest.m

This refactors the SNTFormat tests to use the SNTMetricSet to generate the
testdata. This keeps the metric service and the SNTMetricSet in sync and
reduces repeated data.
Related to #563

Refactored metric service tests to use a common helper

---

Source/santad/EventProviders/EndpointSecurityTestUtil.h
Source/santad/EventProviders/EndpointSecurityTestUtil.mm
Source/santad/EventProviders/SNTEndpointSecurityManagerTest.mm
Source/santad/SNTApplicationTest.m

EndpointSecurityTestUtil assumed only a single es_subscribe was needed to be called before serving all events. This resulted in listenForLogRequests and listenForDecisionRequests racing each other, which would result in auth events being dropped during tests if listenForLogRequests won the race.
This PR changes mock `es_subscribe` to note specific events we're ready for and switches us to `waitForExpectations` so that we can explicitly declare which expectations to wait for.

Deflake SNTApplicationTest by tracking subscriptions to specific event types

---

Source/santad/BUILD
Source/santad/com.google.santa.daemon.systemextension.entitlements
Testing/build_and_sign.sh
Testing/init_dev_certs.sh
Testing/reset.sh

Revert entitlements change and update the codesign behavior of  `Testing/build_and_sign.sh` to match that of the internal kokoro `sign.sh`.
I misunderstood how our release workflow worked when testing for if https://github.com/google/santa/pull/602 broke anything - as it turns out, our .provisionfile isn't actually used in the release build and we instead use separate keys _and_ the entitlements file, where the actual `codesign` tool fills in TeamIdentifierPrefix. The entitlements arg for the build rule can't nicely fill this in, so remove it for now and instead mirror the kokoro sign.sh behavior within external build_and_sign.sh.

Remove use of entitlements field for the santad build rule

---

Testing/build_and_sign.sh
Testing/init_dev_certs.sh
Testing/start_env.sh

We only create a self-signed cert to sign with if there's no provisionprofile. 
Also add the option to randomize the version string in build_and_sign.sh.

Detect existence of a provisionprofile and use that instead in build_and_sign.sh

---

Source/santactl/BUILD
WORKSPACE

With https://github.com/bazelbuild/rules_apple/pull/1236 merged, we can now use the `provisioning_profile` rule on santactl instead of needing to sign over it with the correct certs. 
This will allow santactl with an included .provisionprofile to actually run without failing the MOLXPC checks (fixes https://github.com/google/santa/issues/595).

Add provisioningprofile for santactl so that it's properly signed

---

README.md

The Upvote project has been archived so we should stop pointing people at it.

README: sync servers; remove Upvote, sort the rest alphabetically.

---

Source/common/SNTPrefixTreeTest.mm

Also switch to using XCTAssert* instead of XCTFail

Tests: ensure SNTPrefixTree test finishes executing at appropriate time

---

Source/santametricservice/BUILD
Source/santametricservice/Formats/SNTMetricRawJSONFormat.m
Source/santametricservice/SNTMetricService.m
Source/santametricservice/SNTMetricServiceTest.m
Source/santametricservice/Writers/BUILD
Source/santametricservice/Writers/SNTMetricHTTPWriter.h
Source/santametricservice/Writers/SNTMetricHTTPWriter.m
Source/santametricservice/Writers/SNTMetricHTTPWriterTest.m

This PR adds support for shipping serialized SNTMetricSets to an HTTP server via POSTs. The HTTP writer posts the serialized metrics one at a time, to ensure order. This comes with the assumption that 99% of the time we're going to be sending a single payload.
It's part of the work for metrics support in #563.

Initial commit of an HTTP writer for SNTMetricSets

---

Source/santactl/BUILD
Source/santactl/Commands/sync/SNTCommandSyncTest.m

This test has been around since early 2016 but has been un-runnable since early 2019.

santactl/sync: Fix tests for santactl/sync

---

.github/workflows/check-markdown-links.yml

This adds a workflow to check for dead links in Markdown files when a PR is submitted.
It replaces #627

Add a workflow for checking links in Markdown files

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santa/Resources/AboutWindow.xib
Source/santa/SNTAboutWindowController.h
Source/santa/SNTAboutWindowController.m
docs/deployment/configuration.md

Some users would like to be able to customize the text being displayed in the Santa.app about window. This is a little bit related to the #660 issue.
Only embarrassing problem: I do not know how to setup dev provisioning profiles and certificates for this project, so I wasn't able to test this at all…
I would need a little help, if you are interested in this small feature.

Add AboutText option for the Santa.app

---

Source/santad/SNTExecutionControllerTest.m

This PR fixes the issue with some of the SNTExecutionController test flakiness. The underlying issue is that we dispatch an even to the SNTEventTable mock in the SNTExecutionController tests.

Fix Flaky Execution Controller Tests

---

Source/santad/SNTExecutionControllerTest.m
Source/santametricservice/Formats/SNTMetricRawJSONFormat.m
Source/santametricservice/Writers/SNTMetricHTTPWriterTest.m

1. OCMock objects don't need stopMocking to be called - it's only necessary to call that in cases where the original object behavior must be restored before the end of the test. Otherwise the mock automatically restores during deallocation.
2. SNTMetricRawJSONFormat still used a plain NSDateFormatter and so was applying timezone calculations. In tests we've switched to using NSISO8601DateFormatter but this requires 10.13 and our deployment target is still 10.9 so I've stuck to applying the UTC timezone to the formatter instead.

Tests: Fix some flaky tests

---

Source/santad/SNTExecutionController.m

Do not store Allow TeamID events in the database

---

Source/santactl/Commands/SNTCommandRule.m

The help text is slightly incorrect. Actual usage of adding is `santactl rule  --teamid --identifier <SOME TEAM ID>`

Update help text for --teamid in santactl

---

Source/common/SNTXPCUnprivilegedControlInterface.h
Source/santactl/Commands/SNTCommandFileInfo.m
Source/santactl/Commands/SNTCommandRule.m
Source/santactl/Commands/SNTCommandStatus.m
Source/santactl/Commands/sync/SNTCommandSyncConstants.h
Source/santactl/Commands/sync/SNTCommandSyncConstants.m
Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
Source/santactl/Commands/sync/SNTCommandSyncTest.m
Source/santad/DataLayer/SNTRuleTable.h
Source/santad/DataLayer/SNTRuleTable.m
Source/santad/DataLayer/SNTRuleTableTest.m
Source/santad/SNTDaemonControlController.m
Source/santad/SNTPolicyProcessor.h
Source/santad/SNTPolicyProcessor.m
docs/details/rules.md

Some more QOL for working and managing team ID rules. Let me know if there's anywhere else I'm missing
Linked issue: https://github.com/google/santa/issues/634

Update santactl fileinfo, sync, and status to show teamID info

---

Source/common/SNTMetricSet.m
Source/common/SNTMetricSetTest.m

In a few cases I forgot to return the correct object from `[SNTMetricSet registerMetrics]`. Normally this isn't an issue as we're only registering metrics once. 
However for unit tests it breaks everything that uses the sharedInstance of the SNTMetricSet.

Fix:  SNTMetricSet reregistering metrics returns wrong metric

---

Source/santad/BUILD
Source/santad/SNTExecutionController.h
Source/santad/SNTExecutionController.m
Source/santad/SNTExecutionControllerTest.m

This PR adds a metric for execution events and updates tests to check for it. 
The singleton unfortunately makes tests order dependent.
Related-issue: #563

Add a simple event counter to SNTExecutionController

---

Source/santad/SNTDaemonControlController.m

Removed the check for export metrics in santad. Metrics are always collected but only exported to a monitoring system when all of the necessary config options are set. Since they're always collected `santactl metrics` should always return metrics data.
Related issues: #563

Fix: santactl metrics command behavior

---

Source/santactl/Commands/SNTCommandRule.m

Linked Issue: https://github.com/google/santa/issues/699

Update misleading santactl rule text to have accurate text for team IDs

---

Source/santad/Logs/SNTEventLog.m
Source/santametricservice/Formats/SNTMetricFormatTestHelper.m
Source/santametricservice/Formats/SNTMetricRawJSONFormat.m
Source/santametricservice/SNTMetricServiceTest.m

I left the `NSDateFormatter`'s from `santactl status` and `santactl fileinfo` as they were as the dates they produce are user-facing.

Project: Explicitly set calendar on ISO8601 dates

---

Source/santad/Logs/SNTSyslogEventLog.m

santad: Don't use proc_pidpath when using ES

---

Source/santad/EventProviders/SNTDeviceManager.mm

Add an explicit annotation for an intentional fallthrough in SNTDeviceManager to remove warnings from `-Wimplicit-fallthrough`.

Add clang annotation for fallthrough

---

Source/santactl/Commands/SNTCommandFileInfo.m
Source/santactl/Commands/SNTCommandFileInfoTest.m

santactl/fileinfo: Update --cert-index usage

---

Source/santactl/Commands/SNTCommandFileInfo.m

santactl/fileinfo: Clarify valid index for cert-index

---

BUILD
Conf/com.google.santa.asl.conf
Conf/com.google.santa.newsyslog.conf
Conf/install.sh

The ASL config is a remnant from when Santa did all logging via ASL before Apple deprecated ASL and replaced it with ULS, which doesn't allow redirecting messages to a file. The old config wasn't causing any problems except that it was handling battling newsyslog for rotation and had different parameters.
The signal change in the newsyslog.conf causes newsyslog to fallback on sending a (harmless) SIGHUP to syslogd, which has no effect on Santa except it also triggers a 10s sleep inside newsyslog between renaming the old file and beginning the compression, which is plenty of time for santad to notice the rename and start writing new logs to the newer file.

Conf: Delete and clean-up ASL conf, enable signaling on newsyslog.conf.

---

Source/santasyncservice/SNTSyncRuleDownload.m

* This fixes a potential bug where the postflight could run even though the rules didn't apply.

rule download: return early on daemon timeout

---

Source/santad/SNTExecutionController.m
Source/santad/SNTExecutionControllerTest.m

santad: only store events if there is a sync server configured

---

Source/santad/EventProviders/SNTEndpointSecurityManager.h
Source/santad/EventProviders/SNTEndpointSecurityManager.mm
Source/santad/Logs/SNTSyslogEventLog.m

This PR streamlines the call paths the utilize `strlcpy`, removing an unnecessary `length` parameter and making use of an existing helper function. This also fixes an off-by-one issue in an existing call to `strlcpy`.

Fix additional strlcpy issue, simplify call paths

---

Source/common/BUILD
Source/common/SNTBlockMessage.h
Source/common/SNTBlockMessage.m
Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/common/SNTDeviceEvent.h
Source/common/SNTDeviceEvent.m
Source/common/SNTXPCNotifierInterface.h
Source/santa/BUILD
Source/santa/Resources/AboutWindow.xib
Source/santa/Resources/DeviceMessageWindow.xib
Source/santa/Resources/MessageWindow.xib
Source/santa/SNTBinaryMessageWindowController.h
Source/santa/SNTBinaryMessageWindowController.m
Source/santa/SNTDeviceMessageWindowController.h
Source/santa/SNTDeviceMessageWindowController.m
Source/santa/SNTMessageWindowController.h
Source/santa/SNTMessageWindowController.m
Source/santa/SNTNotificationManager.m
Source/santad/BUILD
Source/santad/EventProviders/SNTDeviceManager.mm
Source/santad/EventProviders/SNTDeviceManagerTest.mm
Source/santad/SNTApplication.m

* Refactor SNTNotificationManager and SNTMessageWindowController for generalized notification logic
* Add the following popup:

Add a USB device blocking popup.

---

BUILD
Source/santactl/Commands/SNTCommandVersion.m
Source/santad/main.m

This adds the current build version as the final component of the CFBundleVersion (e.g. `2022.2.429612858`) and includes the build version in `santactl version` output:
```
santad          | 2022.2 (build 429612858)
santactl        | 2022.2 (build 429612858)
SantaGUI        | 2022.2 (build 429612858)
```
The CFBundleShortVersionString remains the "product" version to match GH releases. I did not add the build version to the kernel extension as the version formatting there is much more strict and we're likely removing it before the next release anyway.

Project: Add build version to CFBundleVersion

---

Source/santametricservice/Writers/SNTMetricHTTPWriter.m

This PR fixes an issue in the SNTMetricHTTPWriter where it would trigger the timeout consistently due to the timeout condition being in the past.

Fix: Issue with SNTMetricHTTPWriter Timeouts

---

Source/common/SNTSystemInfo.h
Source/common/SNTSystemInfo.m
Source/santasyncservice/SNTSyncConstants.h
Source/santasyncservice/SNTSyncConstants.m
Source/santasyncservice/SNTSyncPreflight.m

This is something that could help us identify some machines. I still haven't managed to properly test custom built Santa versions, so I can only guarantee that it compiles. Sorry.

Add model identifier to preflight request

---

Source/common/BUILD
Source/common/SNTCommon.h
Source/common/SNTCommonEnums.h
Source/common/SNTLogging.h
Source/common/SNTPrefixTree.cc
Source/common/SNTPrefixTree.h
Source/common/SantaCache.h
Source/santactl/BUILD

This should be the last remaining bits of the kernel extension in our codebase
Linked bug: https://github.com/google/santa/issues/738

Remove code guarded by #ifdef kernel macros

---

Source/santad/EventProviders/SNTEndpointSecurityManager.mm

This restores behavior that was recently removed

santad: Clear caches when disks are unmounted.

---

BUILD
Source/santa/BUILD
Source/santabundleservice/BUILD
Source/santactl/BUILD
Source/santad/BUILD
Source/santasyncservice/BUILD
Testing/build_and_sign.sh
helper.bzl
version.bzl

The apple_rules allow versioning using an apple_bundle_version rule that extracts elements from an embedded label. We hadn't been able to use this until now because the kernel extension needed access to the version in a define.

Project: Make versioning dynamic through bazel's --embed-label.

---

.github/workflows/ci.yml
generate_cov.sh

The latest `rules_apple` release makes coverage collection work a little better than before; with the right flags bazel will now generate a merged coverage report for us in a single pass.

Project: Fix coverage collection

---

README.md

Change the link to the raw.githubusercontent.com link so that it's still usable when synced internally.

Update logo image of Santa

---

Source/common/BUILD
Source/santactl/BUILD
Source/santad/BUILD
Source/santametricservice/BUILD
Source/santametricservice/Formats/BUILD
Source/santasyncservice/BUILD

The Objective-C targets in these packages are currently not layering
check clean.  Disabling layering check ensures that they will continue
to build even when we enable layering check for Objective-C within
Google.
We also need to reenable layering_check on proto_library to avoid
internal breakges, due to 1. proto_library still implying cpp for some
code paths, and 2. disabling cpp layering check requires being on an
allowlist.

Disable layering check for Objective-C

---

docs/deployment/configuration.md

This came up in the Mac Admins slack. Updating the docs to clarify that AllowedPathRegex also works with Team ID blocking.

Add "Team ID" to description on AllowedPathRegex

---

Source/common/SNTBlockMessage.m
docs/deployment/configuration.md

This mimics the behavior that `%file_sha%` previously had andmoves `%file_sha%` to the expected behavior or just showing the file's SHA.
Related to #795

GUI: Add %bundle_or_file_sha% translation key

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santasyncservice/SNTSyncEventUpload.m
docs/deployment/configuration.md

Sync: Add option to enable event upload despite clean sync.

---

Source/santa/BUILD
Source/santabundleservice/BUILD
Source/santactl/BUILD
Source/santad/BUILD
Source/santametricservice/BUILD
Source/santasyncservice/BUILD
profiles/BUILD

This PR puts all of the provisioning profiles in a top level `profiles` package.
⚠️ This will break your build until you copy the `provisioningprofile`'s to the `/profiles` directory.

Created a profiles package so provisioning profiles only need to be in one place.

---

.github/workflows/ci.yml

per https://github.com/actions/virtual-environments/issues/5446 macOS-12 is now in public beta this adds it to our build matrix in the CI.

Added macos-12 to the build matrix

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/common/SNTXPCControlInterface.h
Source/santad/SNTDaemonControlController.m
Source/santad/SNTExecutionController.m
Source/santasyncservice/SNTSyncConstants.h
Source/santasyncservice/SNTSyncConstants.m
Source/santasyncservice/SNTSyncPreflight.m
docs/deployment/configuration.md

This config can be enabled by profile or by the sync server and causes the client to upload all events, including those that are explicitly allowed.
Fixes #689

Add config to allow uploading all events

---

Source/santad/EventProviders/EndpointSecurityTestUtil.h
Source/santad/EventProviders/EndpointSecurityTestUtil.mm

This fixes an issue with the ES mock where it was deleting all clients on an unsubscribe.

Fix ES Mock Client Subscription issues

---

Source/santad/SNTSyncdQueue.h
Source/santad/SNTSyncdQueue.m

The `startSyncingEvents` and `stopSyncingEvents` were used in SNTDaemonControlController's `-[setSyncdListener:]` method. This allowed upload requests to wait up to 2 seconds for the now legacy syncd connection to become active. The idea was to smooth out any jitter with the connection. The calls to start and stop event uploading were mistakenly removed in https://github.com/google/santa/pull/775, resulting in no santad initiated uploads from taking place. It also means bundle events would never be uploaded.
This pull request removes these start and stop options. In reality the jitter mitigation didn't accomplish much. If the syncservice were to crash or hang it will take longer than a few seconds for the connection to be re-established. In that case we would be dropping the event …

santad: remove start and stop options from the sync service queue

---

Source/common/SNTBlockMessage.m
docs/deployment/configuration.md

The previous change here (#797) was not backward compatible and would be difficult to roll out. This change restores the previously used key and adds 2 new ones for migration. The previous key is marked deprecated and will be removed in the future.

GUI: Update keys for EventDetailURL.

---

Source/santa/SNTMessageWindowController.m
Source/santa/SNTNotificationManager.m

There are synchronization issues that remain but this change fixes the primary problem that we're not preventing duplicate notifications from being scheduled like we intend.
Part of #791

GUI: Fix message queuing

---

Source/common/SNTConfigurator.m

The property doesn't need to be mutable, updating the type.

SNTConfigurator: remove mutability from sync state dict

---

Source/santasyncservice/SNTSyncPreflight.m

Chatting with @pmarkowsky...it doesn't make much sense to start the sync if we are unable to report key properties to the server such as rule count and client mode.
This pull will stop a preflight if it was unable to contact the daemon.

preflight sync: stop the sync if we cannot communicate with the daemon

---

Source/santasyncservice/SNTSyncManager.m
Source/santasyncservice/SNTSyncPreflight.m

* dispatch_group_wait returns non-zero on error (i.e. timed out)
* also don't log reachability info to santactl

preflight sync: fix dispatch_group_wait return polarity

---

Source/santasyncservice/SNTSyncTest.m

Failing preflight early if the daemonConn doesn't return a response the tests. This fix is a bit awkward, I tried to add the defaults in setUp but then you can't overwrite the stubs in methods that need to do it

syncservice: Fix SNTSyncTest

---

Source/santad/SNTExecutionController.m

Instead of logging that it failed to load the file regardless it killed the process or allowed it afterwards, log whether it was denied or allowed.
Committer: Khaled Fouad <safrout@google.com>

Improve Santa's logs to be more descriptive.

---

Source/common/SNTStoredEvent.h
Source/common/SNTStoredEvent.m
Source/santad/SNTExecutionController.m
Source/santasyncservice/SNTSyncConstants.h
Source/santasyncservice/SNTSyncConstants.m
Source/santasyncservice/SNTSyncEventUpload.m
Source/santasyncservice/SNTSyncTest.m
Source/santasyncservice/testdata/sync_eventupload_input_basic.plist
docs/details/events.md

The team ID cannot be extracted from the signing certificate information, when the binary comes from the App Store. With this PR, we are trying to include it in the event information.

Add team ID to synced events

---

Source/santad/EventProviders/SNTDeviceManager.mm

The blocks were operating on the original message provided by ES instead of the copy that was made.

Use the message copy in the dispatch blocks

---

Source/common/SNTConfigurator.m
Source/common/SNTRule.m

In #846 I forgot that  is only a count of the entries so if the config changes but the number of rules remains the same we would never update the cache. This PR moves the processing of the raw config into the KVO handler code so it is not at all in the hot-path. It also does more checking of types in the rule dictionary processing code.

santad: Improve caching of static rules

---

Source/santad/SNTApplication.m

The previous version could lead to santad having lots of threads stuck waiting for connections

santad: Fix re-establishment of syncservice connection

---

Source/common/santa.proto
Source/santad/Logs/SNTProtobufEventLog.m
Source/santad/Logs/SNTSyslogEventLog.m

santad: Log team ID in execution logs, where available

---

Source/common/SNTConfigurator.m

This PR adds methods to SNTConfigurator to ensure KVO works for those options through out Santa.

Ensure KVO works for USB config options

---

docs/deployment/configuration.md
docs/deployment/getting-started.md
docs/deployment/sync-servers.md
docs/deployment/troubleshooting.md
docs/index.md

Fixes #836 
Quick add of the open source sync server list to the docs. Have added this to its own page with references to the Sync overview page. And an update to the Getting Started page & home page to reference this also.

Add sync server list

---

Source/common/SNTConfigurator.m

Nit change here.
An insider or attacker can read the /var/db/santa/sync-state.plist file to determine allowlisted (or denylisted) locations that bypass Santa restrictions.
Example snippet:
```
❯ sudo cat /var/db/santa/sync-state.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>AllowedPathRegex</key>
<string>^/Users/[\w-]+/(?:workspace|go/bin|go/src|/opt/homebrew/|/usr/local/(?:Caskroom|Cellar|Homebrew|bin)/.*</string>
<key>BlockedPathRegex</key>
<string>^/var/.*/AppTranslocation/.*</string>
</dict>
</plist>
```
Access to this file should require sudo to write/read it.

Sync state plist | only allow santad read+write permissions

---

docs/index.md

Thus far, there is no direct link from the santa.dev website to the project on GitHub.

add link to GitHub in docs

---

Source/santa/SNTBinaryMessageWindowController.m

With this change, the publisher field for an App Store published app will be `App Store (Team
ID: K36BKF7T3D` instead of `Apple Mac OS Application Signing`.
Fixes #758

GUI: For App Store published apps, include team ID.

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santa/SNTNotificationManager.m
docs/deployment/com.google.santa.example.mobileconfig
docs/deployment/configuration.md

When enabled, this option disables *all* GUI notifications from Santa. This is intended for kiosk-style machines where it is not expected for users to _ever_ execute unknown binaries.
Fixes #862

GUI: Add silent mode configuration option.

---

Source/santa/BUILD
Source/santa/SNTNotificationManager.m
Source/santa/SNTNotificationManagerTest.m

This allows users to supplement or replace the Santa UI, as well as trigger post-block tools if needed.
Fixes #869

Santa: Post distributed notification when showing block UI

---

Source/santametricservice/Formats/BUILD
Source/santametricservice/Formats/SNTMetricMonarchJSONFormat.m
Source/santametricservice/Formats/SNTMetricMonarchJSONFormatTest.m
Source/santametricservice/Formats/testdata/json/monarch.json
Source/santametricservice/SNTMetricServiceTest.m

This PR fixes an issue with our Monarch JSON that causes some metrics to be wonky.
Specifically our `endTimestamp` field needs to be the time of the export not the `last_updated` time.

Fix up endTimestamp to be Monarch compliant

---

Source/common/BUILD

This change fixes -wunused-variable warnings. The header is not valid by itself and should be declared as a textual header rather than as a header.

Make SNTCommonEnums a textual header

---

Source/common/santa.proto
Source/gui/SNTNotificationManagerTest.m
Source/santad/BUILD
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h
Source/santad/Logs/EndpointSecurity/Serializers/Serializer.mm
Source/santad/testdata/protobuf/v1/exec.json
Source/santad/testdata/protobuf/v2/exec.json
Source/santad/testdata/protobuf/v4/exec.json
Source/santad/testdata/protobuf/v5/exec.json

Adds the MachineID field to all basic string serialized messages. And moves the field to the top level SantaMessage message type in the proto schema.

Machine id proto

---

Source/common/SNTConfigurator.h

Remove unused `usbBlockMessage` attribute from `SNTConfigurator`.

USB: usbBlockMessage is not being used.

---

Source/common/SNTMetricSet.m
Source/common/SNTMetricSetTest.m
Source/santactl/Commands/SNTCommandMetrics.m
Source/santactl/Commands/testdata/metrics-prettyprint.json
Source/santactl/Commands/testdata/metrics-prettyprint.txt
Source/santametricservice/Formats/SNTMetricFormatTestHelper.m
Source/santametricservice/Formats/SNTMetricMonarchJSONFormat.m
Source/santametricservice/Formats/SNTMetricMonarchJSONFormatTest.m
Source/santametricservice/Formats/testdata/json/monarch.json
Source/santametricservice/Formats/testdata/json/test.json

Fix a bug in `SNTMetricSet` that was producing duplicates of a metric cell when the metric had multiple fields.
- This changes the `santactl metric` command to print metrics with multiple fields as key value pairs e.g. `key=value,key2=value2`
- Updates to JSON test files.

Fix: duplicates bug in SNTMetricSet when using multiple fields

---

Source/common/TestUtils.h
Source/santad/BUILD
Source/santad/EventProviders/SNTEndpointSecurityAuthorizer.h
Source/santad/EventProviders/SNTEndpointSecurityAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityAuthorizerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/EventProviders/SNTEndpointSecurityClientBase.h
Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.h
Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManagerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityEventHandler.h
Source/santad/EventProviders/SNTEndpointSecurityRecorder.h
Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm
Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.h
Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistanceTest.mm
Source/santad/Metrics.h
Source/santad/Metrics.mm
Source/santad/MetricsTest.mm
Source/santad/Santad.mm
Source/santad/SantadDeps.h
Source/santad/SantadDeps.mm
Source/santad/SantadTest.mm
Source/santad/main.mm

Add metrics for event counts and event processing times.
Current design passes a block to ES client message handlers to be called when they're done processing and event.
Alternative considered was to have the ES client message handlers return a disposition (instead of calling a block) and leave the work to the base class. This could work but would add some complexity for clients that processed messages async. Given there are only a few clients, it wouldn't be a huge burden to go this route in the future if it provided advantages.

Event metrics

---

Source/santad/Santad.mm

Ensure the `Authorizer` client is enabled first so that all 3rd party execs have policy appropriately applied.

Change order that ES clients are enabled

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santad/Logs/EndpointSecurity/Writers/Spool.h
Source/santad/Logs/EndpointSecurity/Writers/Spool.mm

Fixes an issue where the "file size" configuration option was instead treated as "batch count".

Update spool to flush on size thresholds instead of batch counts

---

.github/workflows/ci.yml
Source/gui/BUILD
Source/gui/main.m
Source/santabundleservice/BUILD
Source/santactl/BUILD
Source/santad/BUILD
Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.h
Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.mm
Source/santad/EventProviders/EndpointSecurity/Message.h
Source/santad/EventProviders/EndpointSecurity/Message.mm
Source/santad/EventProviders/EndpointSecurity/MessageTest.mm
Source/santad/EventProviders/EndpointSecurity/MockEndpointSecurityAPI.h
Source/santad/EventProviders/SNTEndpointSecurityAuthorizerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManagerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistanceTest.mm
Source/santad/Logs/EndpointSecurity/LoggerTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/UtilitiesTest.mm
Source/santad/SNTCompilerControllerTest.mm
Source/santad/SNTExecutionControllerTest.mm
Source/santad/SantadTest.mm
Source/santametricservice/BUILD
Source/santametricservice/Writers/SNTMetricFileWriter.m
Source/santasyncservice/BUILD
Testing/integration/BUILD
helper.bzl

Removing support for macOS 10.15 now that it is no longer supported by Apple.
Note: Dependent upon https://github.com/google/santa/pull/939 to fix broken test.

Drop macOS 10.15

---

Source/santad/BUILD
Source/santad/DataLayer/WatchItems.h
Source/santad/DataLayer/WatchItems.mm
Source/santad/DataLayer/WatchItemsTest.mm

This PR is another step on the way to upcoming monitoring features. It adds the following:
1. `WatchItems` - An object that loads the watch configuration and maintains the prefix tree of the configuration and the overall set of watched paths. The tree nodes contain `shared_ptr`s to `WatchItemPolicy` objects.
2. `WatchItemPolicy` - Contains the information described in the configuration file
This functionality is not yet integrated into the rest of Santa and is not exercised outside of the tests.

Watch items

---

Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm

Something I was testing slipped into my previous PR and it breaks the test, undoing it.

Tests: Fix SNTEndpointSecurityFileAccessAuthorizerTest

---

Source/santad/BUILD
Source/santad/DataLayer/WatchItems.h
Source/santad/DataLayer/WatchItems.mm
Source/santad/DataLayer/WatchItemsTest.mm
Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.h
Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.mm
Source/santad/EventProviders/EndpointSecurity/MockEndpointSecurityAPI.h
Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/EventProviders/SNTEndpointSecurityClientBase.h
Source/santad/EventProviders/SNTEndpointSecurityEventHandler.h
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.h
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Source/santad/Santad.mm
Source/santad/SantadDeps.mm
Source/santad/SantadTest.mm

This change allows the FS Access client to be dynamically enabled/disabled based on whether or not any configured watch items exist. It also adopts watching the changes to the appropriate config key to see if the config path for watch items is modified.

Dynamically enable/disable FS Access client based on config

---

Source/santad/EventProviders/SNTEndpointSecurityClient.mm

There isn't an underlying bug here, retain counts are still appropriately set. It just looks weird so cleaning it up.

Use the appropriate variable when asynchronously processing auth messages

---

Source/santad/DataLayer/WatchItems.h
Source/santad/DataLayer/WatchItems.mm
Source/santad/DataLayer/WatchItemsTest.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm

This PR addresses two issues:
1. Policies from different configurations could be applied to event types with more than target path (e.g. rename with src/dst) if a config update occurred at the same time as the event being handled.
1. If a config update occurred after a policy was applied but before it was logged, it would be possible to log the new policy version for the event that had the old policy applied.

Address policy consistency issues

---

Source/common/BUILD
Source/common/Platform.h
Source/santad/BUILD
Source/santad/DataLayer/SNTRuleTable.m
Source/santad/DataLayer/WatchItems.mm
Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.h
Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.mm
Source/santad/EventProviders/EndpointSecurity/MockEndpointSecurityAPI.h
Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/EventProviders/SNTEndpointSecurityClientBase.h
Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm
Source/santad/EventProviders/SNTEndpointSecurityEventHandler.h
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Source/santad/Santad.mm

This PR adopts the new ES API to limit received events to only the configured watch paths.

Adopt new ES APIs to monitor target paths

---

Source/common/SNTFileInfoTest.m

This PR updates `SNTFileInfo` unit tests to account for Safari coming from a [cryptex](https://eclecticlight.co/2022/11/16/cryptex-how-a-custom-iphone-is-changing-macos-updates/) on macOS 13. Also skips the KEXT test on macOS 13 due to KEXTs moving into the kernel cache.
Fixes #886

Fix SNTFileInfoTest for macOS 13

---

.github/workflows/fuzz.yml

Meant to do this as part of #976. This PR uses the E2E framework to spin up a VM and runs the fuzzer in it. This will also make it viable (with just a bit more work) to fuzz against a running santad as the existing fuzz tests do.

Run fuzzing in a VM

---

Testing/integration/VM/VMGUI/AppDelegate.m
Testing/integration/VM/VMGUI/BUILD

macOS 12.6.1 changed the private API for this. Since Ventura is now out, go ahead and upgrade to it and use the (new) public API to boot into recoveryOS.

Use new public api for booting VM into recoveryOS

---

.github/workflows/fuzz.yml
Fuzzing/common/MachOParse.mm
Source/common/SNTFileInfo.m
Testing/integration/VM/VMGUI/AppDelegate.m

Fixes a file descriptor leak which was killing fuzzing. Also automatically turns off/destroys the fuzzing VM after it's done instead of waiting for the 15 minute timeout.

Fix SNTFileInfo Fuzzing

---

Source/common/SNTCommonEnums.h
Source/santad/EventProviders/SNTEndpointSecurityClientBase.h
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm

This change makes it possible to make use of the ES cache when operations are completely allowed (not just for read access).

Opportunistically use ES cache when possible

---

Fuzzing/common/MachOParse.mm
Source/common/SNTFileInfo.m

This also includes a guard around MachO command size to ensure the fuzzer doesn't infinite loop. `cmdsize` is checked by the OS during loading, so it would never be an issue in real event processing.

Fuzz embedded plist reading

---

Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm

Adds the missing policy name and version to the serialized output from the basic string serializer.

Add policy version and name to basic string serializer

---

Source/santad/BUILD
Source/santad/DataLayer/WatchItemPolicy.h
Source/santad/DataLayer/WatchItems.h
Source/santad/DataLayer/WatchItems.mm
Source/santad/DataLayer/WatchItemsTest.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm

This change adopts the new config file format proposed here: https://github.com/google/santa/pull/988
This change also adopts the new logic associated with matching instigating processes to matching process configurations - namely that ALL attributes of a configured process must match an instigating process for the policy to apply. (E.g., attributes are AND'd together).
This change also standardizes error handling while parsing the config file to attempt to make error messages more standard and actionable.

Adopt new FS Access Auth config format and policy application logic

---

Source/common/SNTXPCUnprivilegedControlInterface.h
Source/santactl/Commands/SNTCommandStatus.m
Source/santad/BUILD
Source/santad/DataLayer/WatchItems.h
Source/santad/DataLayer/WatchItems.mm
Source/santad/DataLayer/WatchItemsTest.mm
Source/santad/SNTDaemonControlController.h
Source/santad/SNTDaemonControlController.mm
Source/santad/Santad.mm

When there is not a valid config:
```
>>> Watch Items
Enabled                   | No
```
When there is a valid config:
```
>>> Watch Items
Enabled                   | Yes
Policy Version            | v0.1-experimental
Rule Count                | 1
Config Path               | /var/db/santa/file_access_config.plist
Last Policy Update        | 2023/01/11 16:36:08 -0500
```

Add watch item state to santactl status

---

Source/santad/Metrics.h
Source/santad/Metrics.mm
Source/santad/MetricsTest.mm

The XPC wrapper Santa uses (MOLXPCConnection) does its own internal handshake to validate code signatures before switching to the desired XPC interface. The metrics client in santad however isn't subscribed to XPC connection invalidation events, so when metrics service dies XPC itself (not the macops wrapper) tries to be helpful and reconnects the connection using the metrics exporting interface. However the newly restarted metrics service server sees this as a new connection and exposes the interface it's expecting for the handshake. Because of this mismatch, we end up continuously sending export metrics requests which are never handled.

Reconnect to santametrics service on failure

---

Source/common/SNTConfigurator.m

There's a chance this is causing issues with `santactl sync` not picking up the SyncBaseURL.
Reverts google/santa#1003

Revert "Configurator: Apply config updates in non-daemon processes"

---

WORKSPACE

The update to rules_python needed for Swift breaks fuzzing. Pin the version that rules_fuzzing requires in a new target, and shadow rules_python with it in fuzzing.

shadow rules_python for fuzzing

---

Source/santad/BUILD
Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm

Nice little perf win here. In CPU traces, calls into the configurator (both to get the shared instance and looking up properties) constituted a large amount of time. This change reduces calls to get the shared instance, and also only calls to lookup some properties when necessary

Reduce calls into configurator

---

Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
docs/deployment/file-access-auth.md

This fixes an issue in 2023.1 related to the new file access monitoring feature. If a rule had a process exception configured with only a Team ID attribute, and a signed instigating process didn't have a Team ID, the process would mistakenly be marked as allowed. (Missing Team IDs are most common on Apple-signed and adhoc-signed binaries.)

Fix team ID and signing ID checks

---

Source/santametricservice/Writers/SNTMetricHTTPWriter.m

We've seen some intermittent crashes when logging metrics via the SNTMetricHTTPWriter.

Fix: Rewrite the SNTMetricHTTPWriter to avoid potential stack corruption

---

Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm

`SerializeToArray` was doing an extra call to `ByteSizeLong`, but we already had calculated this size when constructing the vector.

Use cached sizes when serializing

---

Source/santad/Logs/EndpointSecurity/Serializers/Serializer.mm
Source/santametricservice/SNTMetricServiceTest.m
Source/santametricservice/Writers/SNTMetricHTTPWriter.m
Source/santametricservice/Writers/SNTMetricHTTPWriterTest.m

This change reworks how timeouts are enforced to remove the need for any `__block` variables.

Rework timeout handling in metrics HTTP writer

---

Source/santad/Logs/EndpointSecurity/Logger.h
Source/santad/Logs/EndpointSecurity/Logger.mm
Source/santad/Logs/EndpointSecurity/Writers/File.h
Source/santad/Logs/EndpointSecurity/Writers/File.mm
Source/santad/Logs/EndpointSecurity/Writers/FileTest.mm
Source/santad/Logs/EndpointSecurity/Writers/Null.h
Source/santad/Logs/EndpointSecurity/Writers/Null.mm
Source/santad/Logs/EndpointSecurity/Writers/Spool.h
Source/santad/Logs/EndpointSecurity/Writers/Spool.mm
Source/santad/Logs/EndpointSecurity/Writers/SpoolTest.mm
Source/santad/Logs/EndpointSecurity/Writers/Syslog.h
Source/santad/Logs/EndpointSecurity/Writers/Syslog.mm
Source/santad/Logs/EndpointSecurity/Writers/Writer.h
Source/santad/Metrics.h
Source/santad/Metrics.mm
Source/santad/MetricsTest.mm
Source/santad/Santad.mm

This change adds basic support for handling a change to the `EventLogType` configuration key. This change does not attempt to change the logger on a live instance due to complexities of swapping out the components in a memory-safe manner. However an attempt is made to flush any outstanding log data and metrics before exiting/restarting.

Restart daemon on log type change

---

Source/santactl/Commands/SNTCommandCheckCache.m
Source/santactl/Commands/SNTCommandMetrics.m
Source/santactl/Commands/SNTCommandRule.m
Source/santactl/Commands/SNTCommandStatus.m
Source/santad/SNTDaemonControlController.mm
Source/santasyncservice/SNTSyncPostflight.m
Source/santasyncservice/SNTSyncPreflight.m
Source/santasyncservice/SNTSyncTest.m

Sadly, clang-format insists on empty blocks spanning multiple lines otherwise this would look a _lot_ cleaner.

santactl & syncservice: Use synchronousRemoteObjectProxy where it makes sense

---

Source/common/SantaVnode.h
Source/santad/BUILD
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Empty.h
Source/santad/Logs/EndpointSecurity/Serializers/Empty.mm
Source/santad/Logs/EndpointSecurity/Serializers/EmptyTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h
Source/santad/Logs/EndpointSecurity/Serializers/Serializer.mm
Source/santad/SNTDecisionCache.h
Source/santad/SNTDecisionCache.mm
Source/santad/SNTDecisionCacheTest.mm

CPU traces were showing a lot of contention in the dispatch blocks synchronizing access to the dictionary. This helps relieve the contention. Also removes a second lookup for a cached decision that was previously necessary on the EXEC logging path.

Replace SNTDecisionCache dictionary with SantaCache

---

.github/workflows/sanitizers.yml
Source/santad/EventProviders/SNTEndpointSecurityAuthorizerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm

* Lower the test count from 10->5 since we're running _just_ over 1 hour and getting killed sometimes
* Set the `event_type` of an `es_message` which was uninitialized causing us to sporadically call `RespondAuthFlags` instead of `RespondAuthResult`. No MSAN for macOS which would have caught this directly :(
* Reinstantiate `mockAuthClient` in each "sub-test" since TSAN sees a data race in mock recording

Small test fixes to make sanitizers happy

---

docs/development/sync-protocol.md

The sync protocol docs have an incorrect diagram. This fixes it.

Fix: correct sync protocol diagram

---

Source/santad/DataLayer/WatchItems.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm

Fixes issue if a previously allowed and cached operation should be denied by a new config.

Clear ES cache when watch items change

---

Source/santactl/Commands/SNTCommandRule.m

Previously validation only applied when using the `--sha256` flag, now it applies to `--identifier` too unless adding a team ID rule. The validation is also a _bit_ more robust.
Fixes #1044

santactl/rule: Validate identifier is a valid SHA-256 for binary/cert rules

---

Source/common/SNTConfigurator.m
Source/common/SNTRule.m
Source/common/SNTRuleTest.m
Source/santad/DataLayer/SNTRuleTableTest.m

Unfortunately we're unable to log that the rule is ignored because SNTLogging depends on SNTConfigurator
Fixes #1047

Config: Ignore static rules with an invalid identifier

---

.github/workflows/ci.yml
.github/workflows/continuous.yml
.github/workflows/e2e.yml
.github/workflows/fuzz.yml
.github/workflows/sanitizers.yml

Hi! 👋🏻
Several of the Github Actions in the repo are using the deprecated Node.js 12 runtime. Github have announced that everyone should move away from the deprecated Node.js runtime as of [this](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) blogpost. 
I've upgraded the deprecated actions to versions that uses non-deprecated runtimes.
Open to feedback if there are any other changes wanted done regarding Github Actions 😄

chore(ci): Upgrade workflows to non-deprecated runtimes

---

Source/common/SystemResources.h
Source/common/SystemResources.mm
Source/common/TestUtils.mm
Source/santad/BUILD
Source/santad/EventProviders/RateLimiter.h
Source/santad/EventProviders/RateLimiter.mm
Source/santad/EventProviders/RateLimiterTest.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/Metrics.h
Source/santad/Metrics.mm
Source/santad/MetricsTest.mm

Implements some very basic rate limiting to prevent run-away configurations swamping the logs.
A future release will add support for per-rule rates, as well as being able to change QPS via config.

Basic rate limiting for File Access Authorizer

---

Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.mm

The SD Card block added in #938 did not operate when an SD Card was inserted into the built in SD Card reader on some Mac models. This is because the SD Card was classed as an internal disk - as show below in this screenshot from Disk Arbitrator:  
This PR splits up the existing if statement to ensure that internally mounted SD Cards are included in the SD Card block.

[BUGFIX] Fix SD Card Block not operating on Internal SD Card Readers

---

Source/common/santa.proto
Source/santad/testdata/protobuf/v1/exec.json
Source/santad/testdata/protobuf/v2/exec.json
Source/santad/testdata/protobuf/v4/exec.json
Source/santad/testdata/protobuf/v5/exec.json
Source/santad/testdata/protobuf/v6/exec.json

This change is necessary in order to properly encode non-UTF8 strings which aren't too uncommon in exec args/envs. Proto spec requires strings to be UTF8.
This is a compatible change - `string --> bytes` type change is safe.. Proto generated via the old schema can be successfully unmarshalled via the new schema.

Change types of repeated args and envs fields

---

Source/gui/SNTDeviceMessageWindowView.swift

Fixes a crash when the remountArgs config key is empty.

GUI: Device event window, handle empty remount args

---

Source/santasyncservice/SNTSyncStage.m
Source/santasyncservice/SNTSyncTest.m

Sync will try stripping both the new longer prefix and the existing short prefix if the response data begins with either. This should have no impact on existing sync servers but will allow sync servers in the future to use the longer prefix if they wish.

sync: Add more complete XSSI prefix to be stripped.

---

Source/santad/BUILD
Source/santad/EventProviders/AuthResultCache.h
Source/santad/EventProviders/AuthResultCache.mm
Source/santad/EventProviders/AuthResultCacheTest.mm
Source/santad/EventProviders/SNTEndpointSecurityAuthorizerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManagerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm
Source/santad/SNTDaemonControlController.mm
Source/santad/Santad.mm
Source/santad/SantadDeps.h
Source/santad/SantadDeps.mm

Collect metrics when the auth result cache is flushed for various reasons.
Sample `santactl metrics` output after running `santactl flushcache` and unmounting a DMG:
```
Metric Name               | /santa/flush_count
Description               | Count of times the auth result cache is flushed by reason
Type                      | SNTMetricTypeCounter
Field                     | Reason=ExplicitCommand
Created                   | 2023-04-20T19:56:39.661Z
Last Updated              | 2023-04-20T19:56:39.661Z
Data                      | 1
Field                     | Reason=FilesystemUnmounted
Created                   | 2023-04-20T19:57:05.904Z
Last Updated              | 2023-04-20T19:57:05.904Z
Data                      | 1
```

Cache flush metrics

---

docs/development/sync-protocol.md

The 'request_clean_sync' field is set here: https://github.com/google/santa/blob/main/Source/santasyncservice/SNTSyncPreflight.m#L76
The constant is defined here: https://github.com/google/santa/blob/main/Source/common/SNTSyncConstants.m#L27

Fix documentation for clean sync field in the preflight request.

---

Source/common/SNTCommonEnums.h
Source/common/SNTStoredEvent.m
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm

Provides some breathing room for upcoming rule types.

Switch SNTEventState to uint64_t, reposition flag values and masks

---

Source/santad/DataLayer/WatchItemPolicy.h
Source/santad/DataLayer/WatchItems.h
Source/santad/DataLayer/WatchItems.mm
Source/santad/DataLayer/WatchItemsTest.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
docs/deployment/file-access-auth.md

Adds support for a new option key in the file monitoring config: `InvertProcessExceptions`. This will allow adding a rule to monitor file access from only specified processes.

Add support to file monitoring config to invert process exceptions

---

docs/development/building.md

This PR adds instructions for how to use config overrides on dev versions of Santa.that was added in #957.

Docs: Added instructions for how to use config-overrides.plist

---

Source/santad/Santad.mm

Also cleanup KVO callback checks that weren't properly checking if values changed.

Don't establish the FAA client pre-macOS 13

---

Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h
Source/santad/EventProviders/EndpointSecurity/Enricher.h
Source/santad/EventProviders/EndpointSecurity/Enricher.mm
Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/EventProviders/SNTEndpointSecurityClientBase.h
Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm
Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm
Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm
Source/santad/Logs/EndpointSecurity/Logger.h
Source/santad/Logs/EndpointSecurity/Logger.mm
Source/santad/Logs/EndpointSecurity/LoggerTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h

Design cleanup. The enricher shouldn't vend shared pointers, and enriched objects don't need to be treated as shared pointers as they move through the processing pipeline.

Return unique_ptr from Enrich instead of shared_ptr

---

Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/EventProviders/SNTEndpointSecurityClientBase.h
Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistanceTest.mm
docs/deployment/file-access-auth.md

This fixes an issue where the default mute set was being unnecessarily unmuted. Auth events from binaries within the default mute set that have very low deadlines (because deemed "critical" by ES) were getting denied, leading to unexpected behavior (such as unstable applications).
Fixes: https://github.com/google/santa/issues/1094 - Note: Tested with the config in the reported issue. Was able to repro the original issue as well as confirm this PR allows iTerm2 to launch and still log relevant FILE_ACCESS events. Note though that binaries in the default mute set will not be logged.

Stop unmuting the default mute set unnecessarily.

---

Source/santactl/Commands/SNTCommandFileInfo.m
Source/santad/DataLayer/SNTRuleTable.m

Tested via `StaticRules` key in the config overrides file.
```
$ santactl fileinfo Source/santad/testdata/binaryrules/cert_hash_allowed_signingid_blocked
Path                   : ...Source/santad/testdata/binaryrules/cert_hash_allowed_signingid_blocked
SHA-256                : a9b62a5f8f9f77f89f8070ff109a5524e0fc67c83d7cc6655821cfd98f2e38ff
SHA-1                  : 1b1b60626f6422cb8f4aed829f0916beb7110bd9
Team ID                : EQHXZ8M8AV
Signing ID             : com.google.blocked_signing_id
Type                   : Executable (arm64, x86_64)
Code-signed            : Yes
Rule                   : Blocked (SigningID)
...
```

Fix precedence for static rule evaluation, santactl fileinfo output

---

Source/common/SNTCommonEnums.h
Source/santad/DataLayer/SNTDatabaseTable.m
Source/santad/DataLayer/SNTRuleTable.m

This change migrates the the SNTRuleType enum to have new values. They are now in order of precedence and allow room to grow for future rule types.
This requires a database version bump.

Migrate to new SNTRuleType enum values

---

.github/workflows/ci.yml

This adds the macOS 13 runner to the ci.yml workflow. 
GitHub actions macOS 13 runner has been in beta as since [April](https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/).

Add macOS 13 to the test matrix

---

Source/santad/SNTPolicyProcessor.m

This fixes an error in rule evaluation that causes the PolicyProcessor to incorrectly use Team ID and Signing ID when code signing is broken.

Fix rule evaluation for TeamID and SigningID rules when encountering invalid signatures

---

docs/development/sync-protocol.md

Couple of formatting changes, added SIGNINGID as a rule type

Update sync-protocol.md to include SIGNINGID rule type

---

Source/common/SNTRule.m
Source/common/SNTRuleTest.m
Source/santad/DataLayer/SNTRuleTable.m
Source/santad/DataLayer/SNTRuleTableTest.m
Source/santad/SNTDecisionCacheTest.mm

This PR enforces the following:
1. Binary and Certificate rule identifiers (sha 256 hex strings) will be converted to lowercase
2. TeamID rule identifiers (10 character alphanumeric strings) will be converted to uppercase
3. SigningID rule identifiers will have the TeamID portion of the rule be converted to uppercase, but the Signing ID portion will be left alone (e.g. `tid:Sid` --> `TID:Sid`)
* However, if the hard coded TeamID "platform" is used, it will not have its case converted
fixes #1131

Enforce expected case for various rule type identifiers

---

Source/santasyncservice/SNTSyncStage.m

Fixes the sync --clean "exponential" backoff to be actually exponential, instead of its current linear version (2, 4, 6, 8, 10).
Suggests an improvement to the log message to indicate that the job will ALWAYS abort after N retries. Previously, it was not clear why it would try 5 times and then give up.
This is motivated by an actual incident on July 26, 2023, where the backoff was insufficient, causing users to be unable to download updated rules.
Previously, a user would see something like this when running sudo santactl sync --clean:
```
sudo santactl sync --clean
Uploaded 1 events
Received 697 rules
Performing request, attempt 1
Received 784 rules
Performing request, attempt 1
Received 715 rules
Performing request, attempt 1
Performing request, attempt 2
Performing request, attempt 3 …
```

Change "exponential" backoff in SNTSyncStage.m to be exponential

---

Source/common/TestUtils.h
Source/common/TestUtils.mm
Source/santad/DataLayer/WatchItemsTest.mm
Source/santad/Logs/EndpointSecurity/Writers/FSSpool/BUILD
Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool.cc
Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool.h
Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_log_batch_writer.cc
Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_test.mm

Santa imposes size limits on the spool directory when using the protobuf logger to help ensure too much disk space isn't used. However when the limit is reached, Santa will attempt to re-estimate the size of the spool directory on every event in the hopes that some space cleared and more logs can be written. However if there are many files in the spool, this will lead to `stat(2)` being called excessively (on every spool file for every logged event).
This change stores the last modification time of the spool directory when a size estimate is requested. If the modification time hasn't changed since the previous call, the old estimate is used instead of computing a new one. Once files are removed, the modification time will change and a new estimate will be gathered.
b/288318170

Check if spool dir has changed before estimating size

---

Source/santasyncservice/SNTSyncPostflight.m
Source/santasyncservice/SNTSyncPreflight.m
Source/santasyncservice/SNTSyncState.h

This also moves sending to the main daemon all settings received during preflight to postflight. Currently, this is inconsistent and some settings are sent during preflight, and others during postflight.
fixes #1137

Only update daemon settings when sync settings explicitly set

---

Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santasyncservice/SNTSyncStage.m

sync: Add SyncExtraHeaders config option.

---

Source/common/TestUtils.h
Source/santad/BUILD
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm

This adds a new cache to the FAA client that caches target paths that are allowed to be read by policy. When future OPEN events are received, if the target isn't being opened for writing, the cache is first checked  to see if the target has previously been allowed. If so, a response is sent immediately without processing the message asynchronously or having to lookup policy.

Add hot cache for targets of read only policies

---

Source/santad/EventProviders/AuthResultCache.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/Metrics.mm

Allows the string displaying the enum to format it using %d.
Fixes the error:
error: format specifies type 'int' but the argument has type 'T' [-Werror,-Wformat]

Cast enum to int

---

Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm
Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm

This adds support for using the new was_mapped_writable flag.
In macOS 13 close events now have a new field was_mapped_writable that lets us track if the file was mmaped writable.  Often developer tools use mmap to avoid large numbers of write syscalls (e.g. the go toolchain) and this improves transitive allow listing with those tools.
Fixes #561.

Add support for was_mmaped_writeable to file write monitoring when using macOS 13+

---

docs/development/sync-protocol.md

Document SigningID and TeamID in the definition of Events in the EventUpload stage

Add SigningID/TeamID to Event definition in sync-protocol.md

---

Source/common/BUILD
WORKSPACE

Addresses buildifier issues that suddenly started.
Example: https://github.com/google/santa/actions/runs/5953025386/job/16146336259?pr=1161

Fix new buildifier issues

---

Source/santad/BUILD
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/Metrics.h
Source/santad/Metrics.mm
Source/santad/MetricsTest.mm

Example output:
```
Metric Name               | /santa/file_access_authorizer/log/count
Description               | Count of times a log is emitted from the File Access Authorizer client
Type                      | SNTMetricTypeCounter
Field                     | config_version=policy.v1,access_type=access,foo=ChromeProfile,status=OK,operation=AuthUnlink,decision=AllowedAuditOnly
Created                   | 2023-08-22T14:30:51.343Z
Last Updated              | 2023-08-22T14:37:21.096Z
Data                      | 2
Field                     | config_version=policy.v1,access_type=access,rule_id=foo,status=OK,operation=AuthOpen,decision=AllowedAuditOnly
Created                   | 2023-08-22T14:37:21.096Z
Last Updated              | 2023-08-22T14:37:21.096Z
Data                      | 1
```

Additional metrics for File Access Authorizer client

---

Source/gui/SNTBinaryMessageWindowController.m

This change makes it so that the `EventDetailText` configuration option is only used when the `EventDetailURL` value is used. If a rule has a custom URL set, it is no longer assumed that the `EventDetailText` value is valid.
A more thorough change could add the ability to set custom button text in addition to the custom URL. But this functionality is not currently necessary and the simpler approach of reverting to the default text was chosen instead.
Note: Current default button text is `Open Event...`

Use default event detail button text when a custom URL is set

---

Testing/lint.sh

`set -xo pipefail` implicitly does this behavior; the script will continue but without masking errors from individual commands.

Use 'set -xo pipefail' instead for lint.sh

---

.github/workflows/ci.yml

This PR pins our GitHub actions in the CI workflow to specific versions to prevent tags / other versions from impacting us.
Specifically I used [ratchet](https://github.com/sethvargo/ratchet) to do this.
Steps taken in case someone needs to do this in the future 
1. Make a new branch
2. Run `ratchet pin ./ci.yml`
3. Commit and make a PR
To update actions you'll need to unpin and then redo this.

Pin GitHub Actions to Specific Versions

---

Source/common/BUILD
Source/common/SNTBlockMessage.h
Source/common/SNTBlockMessage.m
Source/common/SNTBlockMessageTest.m
Source/common/SNTXPCNotifierInterface.h
Source/gui/SNTFileAccessMessageWindowController.h
Source/gui/SNTFileAccessMessageWindowController.m
Source/gui/SNTFileAccessMessageWindowView.swift
Source/gui/SNTNotificationManager.m
Source/santad/DataLayer/WatchItemPolicy.h
Source/santad/DataLayer/WatchItems.h
Source/santad/DataLayer/WatchItems.mm
Source/santad/DataLayer/WatchItemsTest.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.h
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/Santad.mm
docs/deployment/configuration.md
docs/deployment/file-access-auth.md
docs/index.md

Adds support for FAA config keys:
* `EventDetailURL` - controls the "open" button in the UI dialog
* `EventDetailText` - controls the button text
These keys can be set at the top level to apply to all rules. Additionally, they can be set as a per-rule option that will override the top level policy if set.

Add ability to specify custom event URLs and button text for FAA dialog

---

Source/santactl/Commands/SNTCommandSync.m

Previously the sync command required root in order to establish a connection to santad with enough privilege to use the XPC methods for adding rules. Now that santasyncservice exists this requirement is no longer necessary and there is no risk in allowing unprivileged users to initiate a sync.
We still ensure that privileges are dropped, just in case someone does execute as root.
Fixes #1195

santactl/sync: Drop root requirement

---

README.md

Replace the mention of the deprecated KEXT in README.md with a mention of the system extension. 
Fixes #1201

Remove mention of KEXT from README.md

---

docs/deployment/configuration.md

Update the configuration.md document to note that FCM based push notifications are not currently available outside the internal Google deployment of Santa

Update configuration.md that push notifications not widely available

---

docs/introduction/syncing-overview.md

Update the syncing-overview.md document to note that FCM based push notifications are not currently available outside the internal Google deployment of Santa

Update syncing-overview.md with note on push notifications

---

Source/santactl/Commands/SNTCommandFileInfo.m

Sample output:
```
$ santactl fileinfo --bundleinfo /Applications/Santa.app/Contents/MacOS/santactl                                                                                                                                                                    4s
Path                   : /Applications/Santa.app/Contents/MacOS/santactl
SHA-256                : 3428cbc14da97951271cc325e1b4f5a4ab3d5d162b2300058f98f924a5706ed7
SHA-1                  : ce46472d60da392f5288abb04e16ee2b7ca47fa3
Bundle Name            : santactl
Bundle Version         : 9999.1.1
Bundle Version Str     : 9999.1
Team ID                : EQHXZ8M8AV
Signing ID             : com.google.santa.ctl
Type                   : Executable (arm64)
Code-signed            : Yes
Rule                   : Allowed (Binary)
Signing …
```

Support printing bundle info via santactl fileinfo command

---

Source/common/SNTCommonEnums.h
Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/santad/BUILD
Source/santad/EventProviders/DiskArbitrationTestUtil.h
Source/santad/EventProviders/DiskArbitrationTestUtil.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.h
Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManagerTest.mm
Source/santad/Santad.mm
docs/deployment/configuration.md

This PR adds a new configuration option, `OnStartUSBOptions`, currently supporting two values: `Unmount` and `ForceUnmount`.
When Santa starts up, if this option is set it will unmount mass storage devices that don't have appropriate flags set (as defined by the `RemountUSBMode` option).

Unmount USB on start

---

Source/santactl/Commands/SNTCommandStatus.m

Normal output:
```
...
>>> Daemon Info
Mode                      | Monitor
Log Type                  | file
File Logging              | Yes
USB Blocking              | Yes
USB Remounting Mode       | noexec, rdonly
On Start USB Options      | ForceUnmount
...
```
JSON output:
```
...
"daemon" : {
"watchdog_ram_events" : 0,
"block_usb" : true,
"log_type" : "file",
"mode" : "Monitor",
"watchdog_cpu_events" : 0,
"driver_connected" : true,
"file_logging" : true,
"remount_usb_mode" : [
"noexec",
"rdonly"
],
"on_start_usb_options" : "Remount"
},
...
```

Add OnStartUSBOptions to santactl status

---

Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManagerTest.mm

Fixes issue where APFS drives were not being properly mounted due to unsupported options being sent to `mount_apfs`.
Credit to @kallsyms for finding the issue

Fix remount issue for APFS formatted drives

---

Source/santactl/Commands/SNTCommandStatus.m
Source/santad/EventProviders/SNTEndpointSecurityDeviceManager.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManagerTest.mm

Changes behavior of #1216 (support remount on startup) to only remount if the remount args are set. The makes for consistent behavior of the runtime mount protections which will leave a device unmounted if the remount args aren't set.

Only remount on startup if remount args are set

---

.github/workflows/e2e.yml

Need to dismiss the blocked executable dialog that comes up from integration tests.

Dismiss santa popup after integration tests

---

Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm

GoogleTest when built with GTEST_HAS_ABSL fails to convert these strings to a `std::string_view`. Lets instead explicitly convert them to a `std::string_view`.

Explicitly cast strings to std::string_view

---

.github/workflows/check-markdown.yml

This PR adds names to the steps in the check-markdown workflow to make it easier to spot what's wrong.
It also pins the steps in the workflow.

Add name for white space check 

---

Source/common/PrefixTree.h
Source/common/SNTCachedDecision.h
Source/common/SNTConfigurator.h
Source/common/SNTConfigurator.m
Source/common/santa.proto
Source/santad/BUILD
Source/santad/EventProviders/AuthResultCache.h
Source/santad/EventProviders/AuthResultCache.mm
Source/santad/EventProviders/AuthResultCacheTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/SNTExecutionController.h
Source/santad/SNTExecutionController.mm
Source/santad/SNTExecutionControllerTest.mm
Source/santad/SNTPolicyProcessor.h
Source/santad/SNTPolicyProcessor.m
Source/santad/Santad.mm
Source/santad/SantadDeps.mm
Source/santad/testdata/protobuf/v1/exec.json
Source/santad/testdata/protobuf/v2/exec.json
Source/santad/testdata/protobuf/v4/exec.json
Source/santad/testdata/protobuf/v5/exec.json
Source/santad/testdata/protobuf/v6/exec.json
docs/deployment/configuration.md

Adds two configuration options supporting entitlement logging:
* `EntitlementsTeamIDFilter` - Filter out entitlements from binaries from configured organizations
* `EntitlementsPrefixFilter` - Filter out specific entitlement prefixes

Entitlements logging config options

---

Source/santad/BUILD
Source/santad/SNTPolicyProcessor.m

This is experimental code only and will be stripped out before the next release.
Sample metric output:
```
Metric Name               | /santa/tmp_signing_info_experiment
Description               | Temporary experiment for dev signed code
Type                      | SNTMetricTypeCounter
Field                     | CSDevFlagSet=False,ValidationCategory=False,DevOIDSet=False
Created                   | 2023-11-20T15:46:32.345Z
Last Updated              | 2023-11-20T15:57:55.462Z
Data                      | 58
Field                     | CSDevFlagSet=True,ValidationCategory=True,DevOIDSet=True
Created                   | 2023-11-20T15:55:42.191Z
Last Updated              | 2023-11-20T15:55:42.191Z
Data                      | 1
```
Sample log line (note: test code changed to force this …

Experimental metrics

---

Source/santad/BUILD
Source/santad/SNTPolicyProcessor.m

In order for TID/SID rules to apply to execs, the binary must not be signed with a development cert.
This cleans up the experiment added in #1238

Ignore TeamID and SigningID rules for dev signed code

---

.bazelrc

Move to C++20 for at-desk builds. The released binaries are already built with C++20.

Bump to C++20

---

.bazelrc
Source/common/SantaCacheTest.mm

Due to internal reasons, we need to continue on C++17 for now.

Revert back to C++17 for now

---

.github/workflows/e2e.yml
Testing/integration/test_config_changes.sh

Reorder "provisioning profile only" tests to run before the sync server is started. With #1217 fixed, `santactl` gets the proper sync server usb block state which was causing these tests to fail.

reorder e2e tests

---

Source/common/BUILD
Source/common/ScopedCFTypeRef.h
Source/common/ScopedCFTypeRefTest.mm
Source/common/ScopedIOObjectRef.h
Source/common/ScopedIOObjectRefTest.mm
Source/common/ScopedTypeRef.h
Source/santad/BUILD
Source/santad/Logs/EndpointSecurity/Serializers/Utilities.h
Source/santad/Logs/EndpointSecurity/Serializers/Utilities.mm
Source/santad/SNTCompilerController.mm

New types to handle automatic releasing. Only basic functionality has been added for now. Can expand upon as needed.

Initial support for some scoped types

---

Source/santad/BUILD
Source/santad/Metrics.h
Source/santad/Metrics.mm
Source/santad/MetricsTest.mm

The previous method had an issue where state wasn't properly carried over when values were flushed after metrics collection.

Fix issue with drop count calculations

---

Source/santactl/BUILD
Source/santactl/Commands/SNTCommandRule.h
Source/santactl/Commands/SNTCommandRule.m
Source/santactl/Commands/SNTCommandRuleTest.mm

The command `santactl rule --check` is merely meant to print primary rule information (either static rule if it exists or what's in the rule database). It is not meant to have any policy applied (either as defined by configuration or hard coded Santa logic that is always enforced).
This PR fixes the rule check output by ensuring policy isn't applied, instead the rule is directly fetched and stringified.
(If a user wants to see how policy would be applied, they must use the `santactl fileinfo` command which requires a binary path to evaluate.)
Fixes #1261

Fix `santactl rule --check`

---

Source/santad/EventProviders/SNTEndpointSecurityRecorder.mm
Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm

This PR adds back support for this configuration key that was inadvertently removed in v2022.9.
The default value is meant to be `false`. However since v2022.9, this value has effectively been hardcoded to `true`. This change fixes the logic back to the original intention.
**IMPORTANT: This means that if you want `FORK`/`EXIT` events to continue to be logged, you must set the `EnableForkAndExitLogging` config key to `true`**
Fixes #1269

Add back support for EnableForkAndExitLogging config key

---

Source/common/SNTConfigurator.h
Source/common/SNTKVOManager.h

chore: Fix multiple typos

---

Source/santactl/Commands/SNTCommandRule.m
Source/santactl/Commands/SNTCommandStatus.m

Fix for #1276 
Also fixes a typo in `SNTCommandRule.m`.

Make santactl status always print out transitive rule status if set 

---

Source/santad/ProcessTree/BUILD
Source/santad/ProcessTree/process_tree.h

ProcessTree: fix missing direct deps

---

Source/common/BUILD
Source/common/SNTRuleIdentifiers.h
Source/common/SNTRuleIdentifiers.m
Source/common/SNTXPCControlInterface.h
Source/common/SNTXPCUnprivilegedControlInterface.h
Source/santactl/BUILD
Source/santactl/Commands/SNTCommandRule.m
Source/santactl/Commands/SNTCommandStatus.m
Source/santad/BUILD
Source/santad/DataLayer/SNTRuleTable.h
Source/santad/DataLayer/SNTRuleTable.m
Source/santad/DataLayer/SNTRuleTableTest.m
Source/santad/SNTCompilerController.mm
Source/santad/SNTDaemonControlController.mm
Source/santad/SNTExecutionControllerTest.mm
Source/santad/SNTPolicyProcessor.m
Source/santasyncservice/SNTSyncPreflight.m
Source/santasyncservice/SNTSyncTest.m

This change streamlines rule lookups and rule count lookups. The goal is to make it easier to add supported rule types by reducing the number of interface changes required.
This PR is not intended to introduce/change any functionality.

Refactor rule and count lookups

---

Source/santactl/Commands/SNTCommandRule.m

This PR adds `--clean` and `--clean-all` flags to the `santactl rule` command to allow clearing the rule database when importing rules via JSON.
Fixes #1293

Added clean flags for JSON rule import

---

Source/common/SNTRuleIdentifiers.h
Source/common/SNTRuleIdentifiers.m

This fixes an issue with santactl fileinfo that stems from SNTRuleIdentifiers not implementing the NSSecureCoding protocol.
This would result in a stacktrace when a user went to use santactl fileinfo.

Implement NSSecureCoding for SNTRuleIdentifiers

---

Source/santad/DataLayer/SNTRuleTable.m
Source/santad/DataLayer/SNTRuleTableTest.m

This PR changes the caching behavior of santad when it receives block rules from that sync service that are already in the database.

Fix: Do not flush authcache when receiving duplicate block rules from the sync service

---

Source/common/SNTConfigurator.m

This change disables applying the config overrides file when running tests by default. You can override this behavior by setting the environment variable `ENABLE_CONFIG_OVERRIDES`. E.g.:
```
bazel test --test_env=ENABLE_CONFIG_OVERRIDES=1 ...other test args...
```

Overrides disabled when running tests unless explicitly enabled

---

Source/gui/Resources/MessageWindow.xib
Source/gui/SNTBinaryMessageWindowController.m
Source/gui/SNTFileAccessMessageWindowView.swift

[Bug] Restore default button type to MessageWindow for blocked events
At some point in macOS 14 with the latest few agent revisions, the MessageWindow needs a hidden titlebar in order for the default button to show.
This is more of a stop-gap measure until this can be rewritten in SwiftUI, which I don't mind taking in the coming weeks to help contribute that change back. 
@russellhancox --> #1006 --> I can probs take the MessageWindow in the coming weeks.
For now, this UI bug can be quickly restored without much effort and decrease UX issues/confusion reported from our users.
- Add hidden title bar to the MessageWindow box so the default button from this prior PR, #788, works again
- Update other SwiftUI buttons to inherit the same behavior
- Keep UX uniformity with this change
- from …

[Bug] Restore `default button type` to `MessageWindow` for blocked events

---

Source/common/SNTXPCControlInterface.m
Source/santactl/Commands/SNTCommandFileInfo.m
Source/santactl/Commands/SNTCommandRule.m
Source/santad/SNTExecutionControllerTest.mm
Source/santad/SNTPolicyProcessor.m

This updates our use of MOLCodesignChecker to use the new interfaces provided in https://github.com/google/macops-molcodesignchecker/pull/13. 
This fixes #1318.

Fix: Update code to use the  new MOLCodesignChecker interfaces for codesigning info

---

.github/workflows/ci.yml

GitHub [now supports Sonoma runners](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) for GitHub actions.

Add macOS-14 to the test matrix

---

Source/santad/BUILD
Source/santad/ProcessTree/BUILD
Source/santad/ProcessTree/annotations/BUILD
Source/santad/ProcessTree/annotations/originator.cc
Source/santad/ProcessTree/annotations/originator.h
Source/santad/ProcessTree/annotations/originator_test.mm
Source/santad/ProcessTree/process_tree.proto
Source/santad/SantadDeps.mm

This PR adds the first annotator to the tree and to Santa, allowing processes to be labeled with which of a handful of potentially long-running "originators" created the process. Current tracked originators are `/usr/bin/login` and `/usr/sbin/cron`.

ProcessTree: add the first annotation, originator (4/4)

---

.github/workflows/e2e.yml
Testing/integration/VM/VMCLI/main.m
Testing/integration/VM/setup.sh
Testing/integration/actions/start_vm.py
Testing/integration/actions/update_vm.py

This PR updates the E2E test pipeline to register ephemeral just in time runners via the GitHub API and dynamically inject the runner token into the VM. This means VM images no longer have any keys inside of them, and they won't expire if unused.
This also splits the start_vm script into 2, one to update the image (if applicable) and the other to register a runner and start the VM.

Testing: update E2E to use JIT runners

---

Source/common/BUILD
Source/common/SNTBlockMessage.m
Source/common/SNTBlockMessageTest.m
Source/common/SNTFileAccessEvent.h
Source/common/SNTFileAccessEvent.m

Add the following template keys to SNTBlockMessage:
* `%file_bundle_id%`  The bundle id of the binary, if any.
* `%team_id%` The Team ID if present in the signature information.
* `%signing_id%` The Signing ID if present in the signature information.
* `%cdhash%`  If signed, the CDHash.
Also refactor `SNTFileAccessEvent` slightly. Make it a subclass of `SNTStoredEvent` to avoid redefining common properties.

SNTBlockMessage: add more template options

---

Source/santad/BUILD

This is to fix an issue with the dependencies for the SNTPolicyProcessor test.

Add necessary dep for SNTPolicyProcessorTest

---

Source/santad/EventProviders/SNTEndpointSecurityClient.mm

The use of the background queue is a historical artifact from when Santa had its own kernel extension with separate in-kernel queues for processing AUTH & NOTIFY type events. With the move to ES and the larger number of event types that we now notify on, running at the background QoS carries a small risk that the thread processing these events is not given a chance to run often enough that the queue grows and increases memory usage.

santad: Bump QoS of notify handling queue

---

docs/known-limitations.md

Fixed some grammar and correctness with this file.

Update Minor Grammar & Correctness issues within known-limitations file of docs.

---

Source/santad/EventProviders/SNTEndpointSecurityClient.mm

Bumping from BACKGROUND to DEFAULT had the desired impact of processing events faster and reducing memory usage but had a larger-than-expected increase in CPU usage. UTILITY is in the middle of these two and better fits the desired priority.

santad: Drop QoS of notify handling queue

---

Source/santad/BUILD
Source/santad/EventProviders/EndpointSecurity/Message.h
Source/santad/EventProviders/EndpointSecurity/Message.mm
Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/Metrics.h
Source/santad/Metrics.mm
Source/santad/MetricsTest.mm
Source/santad/SNTExecutionController.mm
Source/santad/SNTPolicyProcessor.h
Source/santad/SNTPolicyProcessor.mm

Adds a new metric that tracks cases where the file reported in EXEC events is not the same file currently on disk.
Test setup:
Create some binary named `t`. In one terminal, run the following to rapidly change `t` devno/inode pair:
```
cp t t1
cp t t2
while [[ true ]]; do rm ./t; cp ./t1 ./t; sleep 0; rm ./t; cp ./t2 ./t; sleep 0; done
```
In a second terminal, continuously execute the binary:
```
while [[ true ]]; do ./t > /dev/null; done
```
Sample `santactl metrics` output:
```
Metric Name               | /santa/event_stat_change_count
Description               | Count of times a stat info changed for a binary being evalauted
Type                      | SNTMetricTypeCounter
Field                     | step=MessageCreate,error=0
Created                   | 2024-05-15T00:47:07.050Z
Last …
```

Add metric for when the file on disk is not the file being evaluated

---

Source/common/SNTCommonEnums.h
Source/santad/BUILD
Source/santad/EventProviders/EndpointSecurity/Message.h
Source/santad/EventProviders/EndpointSecurity/Message.mm
Source/santad/EventProviders/SNTEndpointSecurityClient.mm
Source/santad/Metrics.h
Source/santad/Metrics.mm
Source/santad/MetricsTest.mm
Source/santad/SNTExecutionController.mm

Also refactor setting metrics to be more general.

Fix stat metrics accounting.

---

Source/common/SNTFileAccessEvent.m

This prevented the FAA dialog popups from displaying.
Caused by: #1337

Fix NSSecureCoding adoption in SNTFileAccessEvent

---

Source/santactl/Commands/SNTCommandRule.m

Also fixes the calculation of CDHash rules from a file.

santactl/rule: Allow adding signing ID and team ID rules by file path

---

Source/santad/EventProviders/SNTEndpointSecurityTamperResistance.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistanceTest.mm

Root users can currently kill the `com.google.santa.daemon` process. It will be immediately restarted by sysextd but this opens a very brief window where protection is lost. Hooking `ES_EVENT_TYPE_AUTH_SIGNAL` and blocking all signals to the santad process prevents this and it doesn't interfere with upgrades.

santad: Add signal auth to tamper resistence.

---

Source/common/BUILD
Source/common/SigningIDHelpers.h
Source/common/SigningIDHelpers.m
Source/santabundleservice/BUILD
Source/santabundleservice/SNTBundleService.m
Source/santactl/BUILD
Source/santactl/Commands/SNTCommandFileInfo.m
Source/santad/BUILD
Source/santad/SNTPolicyProcessor.mm

This PR adds a helper function to format the Signing IDs in Santa and to ensure they're always handled and formatted the same way.
It's marked draft until we're sure that it's used everywhere it should be and that folks are happy with it.

Add a Signing ID Format Helper

---

docs/development/contributing.md

**What does this change?**
ISSUE-1325 ( #1325 ) identified that Identifier conventions were not documented.  This change modifies the `contributing.md` file to include the following information
-----
All submissions related to the use of different identifiers should adhere to the following conventions.
| Identifier | Notes | Example |
| -------- | ------- | ------- |
| SHA-256  | lowercase |  `801d1dd8bc78984c126a269aca053642d16eef4389dfdc8df575af929fdcf279` |
| CDHash | lowercase | `2d1cff4b1080058e7e5913e5a3398bcd0199b6a4` | 
| TeamID | uppercase | `43AQ936H96` |
| Signing ID | case insensitive | `EQHXZ8M8AV:com.google.Chrome` |

docs(ISSUE-1325): Add Identifier Conventions

---

Source/santad/EventProviders/SNTEndpointSecurityAuthorizerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityDeviceManagerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Source/santad/EventProviders/SNTEndpointSecurityRecorderTest.mm
Source/santad/EventProviders/SNTEndpointSecurityTamperResistanceTest.mm
Source/santad/Metrics.h

Regression tests for latent issues that can happen when adding subscriptions for new event types.

Add tests to ensure EventTypeToString handles all subscriptions

---

.github/workflows/ci.yml
Source/common/Platform.h
Source/common/SNTMetricSet.m
Source/common/TestUtils.mm
Source/gui/BUILD
Source/gui/main.m
Source/santabundleservice/BUILD
Source/santactl/BUILD
Source/santad/BUILD
Source/santad/DataLayer/SNTRuleTable.m
Source/santad/EventProviders/EndpointSecurity/EndpointSecurityAPI.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Source/santad/Logs/EndpointSecurity/Serializers/Utilities.mm
Source/santad/SNTApplicationCoreMetricsTest.mm
Source/santametricservice/BUILD
Source/santametricservice/Formats/SNTMetricFormatTestHelper.m
Source/santametricservice/Formats/SNTMetricMonarchJSONFormat.m
Source/santasyncservice/BUILD
Testing/integration/BUILD
helper.bzl

Set the minimum supported OS to macOS 12, dropping support for macOS 11.
Justification is twofold:
1. Apple only supports "current - 2" versions with security updates. Santa aims to meet this goal as well. This means macOS 11 hasn't been supported in some time already.
2. The macOS 11 test runners are being removed on GitHub, so we don't have a automated test pipeline anymore.

Drop macos 11

---

Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm

Adds in the string serialization support for the new login/logout event types added in #1371

Add string serialization for new login/logout events

---

Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Source/santad/testdata/protobuf/v6/login_login.json
Source/santad/testdata/protobuf/v6/login_login_failed_attempt.json
Source/santad/testdata/protobuf/v6/lw_session_lock.json
Source/santad/testdata/protobuf/v6/lw_session_login.json
Source/santad/testdata/protobuf/v6/lw_session_logout.json
Source/santad/testdata/protobuf/v6/lw_session_unlock.json
Source/santad/testdata/protobuf/v6/openssh_login.json
Source/santad/testdata/protobuf/v6/openssh_login_failed_attempt.json
Source/santad/testdata/protobuf/v6/openssh_logout.json
Source/santad/testdata/protobuf/v6/screensharing_attach.json
Source/santad/testdata/protobuf/v6/screensharing_attach_unset_fields.json
Source/santad/testdata/protobuf/v6/screensharing_detach.json

Adds in the protobuf serialization support for the new login/logout event types added in #1371

Add protobuf serialization for new login/logout events

---

Source/santad/EventProviders/EndpointSecurity/EnrichedTypes.h
Source/santad/EventProviders/EndpointSecurity/Message.h
Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
Source/santad/Logs/EndpointSecurity/Serializers/Serializer.mm

Removes the instance method `es_msg()` from the base `EnrichedEventType` class in favor of using the class member access operator.

Use class member access operator for underlying ES message

---

Source/santasyncservice/SNTSyncEventUpload.mm
Source/santasyncservice/SNTSyncPostflight.mm
Source/santasyncservice/SNTSyncPreflight.mm
Source/santasyncservice/SNTSyncRuleDownload.mm
Source/santasyncservice/syncv1.proto

This PR adds a `machine_id` field to all of the Request messages in the proto version of the sync protocol. 
This is to enable a GRPC based version of the sync protocol.

Add machine_id to facilitate a GRPC version of the sync protocol

---

Source/santasyncservice/SNTSyncStage.mm

If we receive a non-200 HTTP response, we should return an error instead of parsing the response to an empty protobuf message.

Handle non-200 HTTP responses in SNTSyncStage performRequest

---

Source/common/SigningIDHelpers.m

This log line gets spit out in santactl fileinfo output in a way that makes the command harder to use for various things

common: Remove debug log when signing ID is missing.

---

Source/common/SNTConfigurator.m
Source/santasyncservice/SNTSyncPreflight.mm
Source/santasyncservice/SNTSyncRuleDownload.mm
Source/santasyncservice/SNTSyncTest.mm
Source/santasyncservice/syncv1.proto
docs/deployment/configuration.md
docs/development/sync-protocol.md

This change makes it so that nearly all sync protocol response fields are not required, and defines action taken by Santa when given keys are not set. It additionally standardizes more configuration into enum fields.

Improve handling of sync response default values

---

Source/common/SNTSystemInfo.h
Source/common/SNTSystemInfo.m
Source/santad/BUILD
Source/santad/main.mm
Source/santasyncservice/SNTSyncPreflight.mm
Source/santasyncservice/SNTSyncStage.mm
Source/santasyncservice/SNTSyncTest.mm
Source/santasyncservice/syncv1.proto
Source/santasyncservice/testdata/sync_preflight_request.json

Disable the `preserve_proto_field_names` option when marshalling JSON requests as this prevents the `json_name` attribute on fields from working properly. Add that attribute to all fields so that they marshal as expected. Stop setting the `always_print_enums_as_ints` option as the value we're setting to is the default anyway.
Also add a test that preflight request data looks as expected.

sync: Fix serial_num field name

---

Source/santasyncservice/BUILD
Source/santasyncservice/SNTSyncFCM.m
Source/santasyncservice/SNTSyncManager.m

SCNetworkReachability is deprecated. It also causes occasional crashes.

sync: Upgrade from SCNetworkReachability -> nw_path_monitor

---

Source/santasyncservice/SNTSyncManager.m
Source/santasyncservice/SNTSyncStage.mm

Don't retry requests if the error is that the machine is offline

sync: Improve logging when connection restored, avoid retries.

---

Source/santasyncservice/SNTSyncPostflight.mm
Source/santasyncservice/syncv1.proto

This lets the protobuf json serializer to send the values as ints (like NSJSONSerialization did) instead of strings. This will cause problems if someone has 4B rules but that's probably a sign of bigger problems

sync: Drop rules_* fields in postflight to uint32

---

Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm

Fixes crash due to improper check safeguarding access to the TTY member of the `es_process_t` struct.
Fixes #1419

Use proper CanWrite method to safeguard TTY struct access

---

Source/santad/EventProviders/SNTEndpointSecurityAuthorizer.mm
Source/santasyncservice/SNTSyncEventUpload.mm
Source/santasyncservice/syncv1.proto
docs/development/sync-protocol.md

Change the uint64 fields in the syncv1.proto to uint32 to ensure backwards compatibility.
This also updates the SNTSyncEventUpload code to use the uint32 values and updates sync protocol docs to define the integer fields as `uint32` explicitly.

Fix: Change uint64 fields in syncv1.proto to uint32 for backwards compatibility
