google/santa

- Source/santad/SNTEventLog.m
I am breaking it into small commits to make it easy to be reviewed and merged in
> Optimize logging by using one pre-allocated NSMutableString

- Source/common/SNTFileInfo.m
pread can return less than the chunk size (e.g. signal caught in the
middle) and hence we need to handle it. This change also cleans up the
hash function and makes it more performant.
> Correctly use pread

- Source/SantaGUI/Resources/MessageWindow.xib
- Source/santa-driver/SantaDecisionManager.cc
- Source/santa-driver/SantaDecisionManager.h
- Source/santa-driver/SantaDriverClient.cc
- Source/santad/SNTEventLog.m
- Source/santad/SNTExecutionController.m
Mostly perf improvements:
* Use msleep/wakeup instead of sleeping for a fixed period while waiting for responses from daemon
* Cache user/group id->name lookups as getpwuid/getgrgid can be quite slow
* Rename the Dismiss button to Ignore
> Performance improvements

- Source/common/SNTBlockMessage.m
- Source/santa-driver/SantaDecisionManager.cc
- Source/santa-driver/SantaDecisionManager.h
- Source/santad/SNTApplication.m
GUI change: handles bundle URL generation for bundles with just a version, not a short version string. Also refactored slightly to avoid pointless variable expansion.
santad/santa-driver: Improve performance by reducing load on santad and preventing the log queue from spawning hundreds of threads.
> Performance improvements, GUI bundle handling

- Source/santactl/Commands/SNTCommandFileInfo.m
*  	Added --json output option. Added --key output option.
*  	Added multi-file processing.
> santactl fileinfo updates

- Source/common/SNTXPCControlInterface.h
- Source/santactl/Commands/SNTCommandFileInfo.m
- Source/santad/DataLayer/SNTRuleTable.h
- Source/santad/DataLayer/SNTRuleTable.m
- Source/santad/SNTDaemonControlController.m
- Source/santad/SNTExecutionController.m
- Tests/LogicTests/SNTExecutionControllerTest.m
- Tests/LogicTests/SNTRuleTableTest.m
*  Squashed binary and cert rule fetching down to one call
> Performance Updates

- Source/santactl/Commands/SNTCommandFileInfo.m
*  perform simultaneous hashing for sha1 & sha256 when we know we have to output both
> santactl fileinfo sha1 & sha256 simultaneous hashing

- Conf/Package/postinstall
- Conf/install.sh
> Package: Ensure /usr/local/bin exists before making symlinks in it.

- Santa.xcodeproj/project.pbxproj
- Source/santactl/Commands/SNTCommandRule.m
> santactl/rule: Handle bad path properly (dir, non-file)

- Santa.xcodeproj/project.pbxproj
- Tests/LogicTests/SNTCommandFileInfoTest.m
*  Argument parsing tests
*  Code signed tests
> SNTCommandFileInfo Tests

- Source/santa-driver/SantaDecisionManager.cc
I had a debug build yesterday causing panics because this wasn't tail-call optimized (which I suppose makes some sense for a debug build) and the stack is very small.
> santa-driver: FetchDecision - use a loop rather than recursing.

- Tests/LogicTests/SNTExecutionControllerTest.m
Fix tests for changes in https://github.com/google/santa/commit/b360e782c6eee601295d273b005eb439a0efa0f3
> Mocking for MOLCodesignChecker initWithBinaryPath:error:

- .gitignore
- README.md
- Rakefile
- Santa.xcodeproj/project.pbxproj
- Santa.xcodeproj/xcshareddata/xcschemes/All.xcscheme
- Santa.xcodeproj/xcshareddata/xcschemes/KernelTests.xcscheme
- Santa.xcodeproj/xcshareddata/xcschemes/LogicTests.xcscheme
- Santa.xcodeproj/xcshareddata/xcschemes/Santa.xcscheme
- Santa.xcodeproj/xcshareddata/xcschemes/santa-driver.xcscheme
- Santa.xcodeproj/xcshareddata/xcschemes/santactl.xcscheme
- Santa.xcodeproj/xcshareddata/xcschemes/santad.xcscheme
- Source/santad/SNTDriverManager.m
- Source/santad/main.m
I've added a note to the README that we currently expect to build with Xcode 7.3.1 as building with Xcode 8 results in numerous issues (see #110).
> Revert changes for building with Xcode 8

- Source/santactl/Commands/SNTCommandFileInfo.m
*  Fixed retain cycle 
*  Added locking for a NSMutableArray when accessed on multiple threads
> SNTCommandFileInfo

- Source/SantaGUI/SNTNotificationManager.m
- Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m
Seems like a good idea to @msuozzo and myself @ 9:45pm. Who knows how it will look in the morning.
> Notification verbage update

- Source/common/SNTXPCConnection.m
- Source/santactl/Commands/SNTCommandCheckCache.m
- Source/santactl/Commands/SNTCommandFileInfo.m
- Source/santactl/Commands/SNTCommandFlushCache.m
- Source/santactl/Commands/SNTCommandRule.m
- Source/santactl/Commands/SNTCommandStatus.m
- Source/santactl/Commands/SNTCommandVersion.m
- Source/santactl/Commands/sync/SNTCommandSync.m
- Source/santactl/SNTCommandController.h
- Source/santactl/SNTCommandController.m
> SNTXPCConnection: make XPC debugging easier

- Source/common/SNTConfigurator.m
*  Creates a default config where ClientMode is set to MONITOR if no config exists or it is deleted
> create default config if one does not exist

- Source/santa-driver/SantaDecisionManager.cc
Cosmetic refactor of the cache expiration calculation in santa-driver.
> santa-driver: Refactor cache expiration calculation

- Conf/com.google.santa.asl.conf
- Rakefile
*  Move the default location of santa.log to mitigate against malware that wipes /var/log/*
*  If /var/db/santa/* is wiped we will at least know it is targeting Santa
> project/config: Move /var/log/santa.log to /var/db/santa/santa.log

- Source/santa-driver/SantaDecisionManager.cc
- Source/santa-driver/SantaDecisionManager.h
> Revert "santa-driver: Prevent possible infinite loop if decision requests fai…"

- Source/santad/SNTApplication.m
- Source/santad/SNTDaemonControlController.h
- Source/santad/SNTDaemonControlController.m
- Source/santad/SNTEventLog.h
- Source/santad/SNTEventLog.m
Let me know if I should add more fields to the log.
> log the events generated by bundle hashing with action=BUNDLE

- Source/santabs/SNTBundleService.m
I have not found a bundle that will return nil for it's path, but they are out there (see stack below). Santa.app is resilient and reverts to using the offending blockable. Santa.app will also start back up santabs. No rush on this.
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSFileManager subpathsOfDirectoryAtPath:error:\]: path is nil'
abort() called
terminating with uncaught exception of type NSException
Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fffa80452cb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffbce5d48d objc_exception_throw + 48
2   CoreFoundation                      0x00007fffa80c3c3d +[NSException raise:format:\] + 205
3 …
> santabs: don't lookup nil bundle paths - santabs will crash

- Source/santa-driver/CircularQueue/EventsCommon.h
- Source/santa-driver/CircularQueue/Queue.c
- Source/santa-driver/CircularQueue/Queue.h
- Source/santa-driver/CircularQueue/QueueAtomic.h
- Source/santa-driver/CircularQueue/QueueCommon.h
- Source/santa-driver/CircularQueue/QueuePlatformExpert.c
- Source/santa-driver/CircularQueue/QueuePlatformExpert.h
- Source/santa-driver/CircularQueue/QueueTypes.h
- Source/santa-driver/CircularQueue/README.md
- Source/santa-driver/SantaDecisionManager.cc
- Source/santa-driver/SantaDecisionManager.h
This PR adds a messaging queue data structure to Santa. Subsequent changes will shuffle things around so as to make updating the events definitions (shared with Linux) and data structure code simpler, and move everything else into the platform expert header.
> Initial commit of the new circular message queue.

- Source/SantaGUI/SNTNotificationManager.m
* Don't display a notification if the config for a custom notification is an empty string
> config: add option to disable mode change notifications

- Podfile.lock
- Source/SantaGUI/SNTMessageWindowController.m
- Source/common/SNTStoredEvent.m
- Source/common/SNTXPCConnection.m
- Source/santabs/SNTBundleService.m
- Source/santactl/Commands/SNTCommandRule.m
- Source/santad/DataLayer/SNTEventTable.m
- Source/santad/DataLayer/SNTRuleTable.m
- Source/santad/SNTEventLog.m
- Source/santad/SNTExecutionController.m
- Source/santad/SNTPolicyProcessor.h
*  All: use common import style for cocoapods <PodName/PodName.h>
*  All: Update Pods
> Import fixes

- Source/santa-driver/SantaDecisionManager.cc
- Source/santa-driver/SantaDecisionManager.h
Also, catch KAUTH_VNODE_APPEND_DATA.
> santa-driver: do not invalidate cached decisions on KAUTH_VNODE_ACCESS

- Source/santa-driver/SantaDecisionManager.cc
> santa-driver: Stop checking hasdirtyblks, the loader handles this

- Source/santa-driver/SantaCache.h
- Source/santa-driver/SantaDecisionManager.h
- Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m
This PR contains some fixes on the documentation (caused warnings when compiling with CMake) and a small check on the santactl executable when retrieving JSON from the syncserver (found with libFuzzer).
> Various fixes (documentation, and an additional check on the JSON received from the syncserver)

- Source/santa-driver/SantaDecisionManager.cc
makes toolchains with "-Werror -Wimplicit-fallthrough" happy
> intentional fall-through

- Source/common/SNTConfigurator.h
- Source/common/SNTConfigurator.m
- Source/common/SNTXPCControlInterface.h
- Source/common/SNTXPCUnprivilegedControlInterface.h
- Source/santactl/Commands/SNTCommandStatus.m
- Source/santactl/Commands/sync/SNTCommandSyncConstants.h
- Source/santactl/Commands/sync/SNTCommandSyncConstants.m
- Source/santactl/Commands/sync/SNTCommandSyncPreflight.m
- Source/santad/SNTDaemonControlController.m
- Source/santad/SNTExecutionController.m
- Source/santad/SNTPolicyProcessor.m
- Tests/LogicTests/SNTExecutionControllerTest.m
Also rename TransitiveWhitelistingEnabled -> EnableTransitiveWhitelisting and BundlesEnabled -> EnableBundles
> common: Allow transitive whitelisting to be controlled by sync servers.

- Docs/deployment/configuration.md
- bundles_enabled became enable_bundles.
- enabled_transitive_whitelisting was added.
Both changes were implemented in #300
> document recent changes sync server configuration

- Source/santad/DataLayer/SNTRuleTable.m
- Tests/LogicTests/SNTRuleTableTest.m
Also add a test to ensure this doesn't change one day without us noticing.
Came from a discussion in #314.
> santad: Document implicit rule ordering

- Conf/uninstall.sh
I think this was added by accident.
> fix uninstall.sh

- Santa.xcodeproj/project.pbxproj
- Source/santa-driver/SantaPrefixTree.cc
- Source/santa-driver/SantaPrefixTree.h
- Tests/LogicTests/SantaPrefixTreeTest.mm
* Serialize add prefix requests.
* Add a bunch of ugly macros to make SantaPrefixTree usable in userspace.
>  SantaPrefixTree: Fix a bug and add some more tests

- BUILD
- WORKSPACE
What do you think about adding buildifier to Santa's WORKSPACE?
https://github.com/bazelbuild/buildtools/tree/master/buildifier
> BUILD: buildifier formatting

- Source/santactl/Commands/SNTCommandFileInfo.m
- WORKSPACE
Also add a specific return string in SNTFileInfo about revoked certs
> Project: Use MOLCodesignChecker v2.1

- Source/santad/SNTSyncdQueue.m
> fix typo (inital -> intial)

- Santa.xcodeproj/project.pbxproj
- Source/common/SNTKernelCommon.h
- Source/santa/SNTAppDelegate.m
- Source/santad/BUILD
- Source/santad/SNTApplication.m
- Source/santad/SNTCompilerController.h
- Source/santad/SNTCompilerController.m
- Source/santad/SNTDaemonControlController.m
- Source/santad/SNTDriverManager.h
- Source/santad/SNTDriverManager.m
- Source/santad/SNTEndpointSecurityManager.h
- Source/santad/SNTEndpointSecurityManager.m
- Source/santad/SNTEventProvider.h
- Source/santad/SNTExecutionController.h
- Source/santad/SNTExecutionController.m
- Source/santad/SNTExecutionControllerTest.m
* Initial EndpointSecurity integration
> add SNTEventProvider interface

- Santa.xcodeproj/project.pbxproj
- Source/common/SNTCommonEnums.h
- Source/common/SNTXPCBundleServiceInterface.h
- Source/common/SNTXPCBundleServiceInterface.m
- Source/santad/SNTDaemonControlController.m
* Nest `santabundleservice.xpc` inside of `com.google.santa.daemon.systemextension`
> update component paths

- Source/santad/Logs/SNTSyslogEventLog.m
This should be much more reliable and, in theory, faster.
> santad: Use args from endpointsecurity rather than using the sysctl

- Santa.xcodeproj/project.pbxproj
- Source/santad/Resources/santad.entitlements
* I couldn't find a variable that worked for `com.apple.developer.team-identifier`. It must exist, I just couldn't find it 🤷‍♂. What I tried:  `$(TeamIdentifier)` , `$(TeamId)`, `$(TeamID)`, `$(Team)`.
> add required santad entitlements

- docs/development/building.md
Will need updating again when we merge endpointsec.
> Docs: update building docs. Fixes #411.

- Santa.xcodeproj/project.pbxproj
- Santa.xcodeproj/xcshareddata/xcschemes/santad.xcscheme
- Source/common/SNTKernelCommon.h
- Source/common/SNTLogging.m
- Source/santad/EventProviders/SNTDriverManager.m
- Source/santad/EventProviders/SNTEndpointSecurityManager.mm
- Source/santad/SNTApplication.m
* Have the EventProvider create and dispatch messages on appropriate queues
* Refactor how copying es message -> santa message fields are done, hopefully in a safer way.
* Fix Xcode project
> com.google.santa.daemon: async es message handling

- Source/santad/SNTExecutionController.m
* lookup the tty for deny decisions before posting the decision
> com.google.santa.daemon: fix tty messages

- Source/santad/EventProviders/SNTEndpointSecurityManager.mm
* deny execs that are about to exceed the es deadline
> com.google.santa.daemon: handle es deadline

- Source/common/SNTConfigurator.h
- Source/common/SNTConfigurator.m
- Source/santad/SNTPolicyProcessor.m
- version.bzl
Also log out a bad signature's error code.
> santad: Add config flag to block all binaries with bad signatures.

- Source/common/SNTFileInfo.m
VLAs complicate static analysis and bloat stack size. Replace VLA allocation with calls to malloc and free
> common: Eliminate VLA usage in SNTFileInfo

- Podfile.lock
- Santa.xcodeproj/project.pbxproj
- Source/common/BUILD
- Source/common/SNTConfigurator.h
- Source/common/SNTConfigurator.m
- Source/common/SNTLogging.m
- Source/common/SNTXPCControlInterface.m
- Source/santa/SNTAppDelegate.m
- Source/santa/main.m
- Source/santactl/Commands/SNTCommandStatus.m
- Source/santactl/Commands/SNTCommandVersion.m
- Source/santad/SNTApplication.m
- Source/santad/main.m
A (sort of) hack to support enterprise managed Macs updating to macOS 10.15+ from previous macOS versions with Santa installed.
Fixes #437
> Config: EnableSystemExtension option

- Conf/Package/postinstall
- Conf/Package/preinstall
- Conf/install.sh
- Source/santad/SNTApplication.m
- Source/santad/main.m
- version.bzl
* Use the logic in com.google.santa.daemon to decide whether to load the kext or SystemExtension.
> Simplify install scripts

- Source/santactl/Commands/sync/SNTCommandSyncRuleDownload.m
- version.bzl
> santactl: sanitize rule payload

- Source/santad/SNTDaemonControlController.m
- Source/santad/SNTPolicyProcessor.h
- Source/santad/SNTPolicyProcessor.m
> santad: Fix decision fetching for certs by hash

- mkdocs.yml
> Docs: fix readthedocs config

- README.md
> Fix video in README

- WORKSPACE
`MOLAuthenticatingURLSession`: _v2.8_ -> _v2.9_
`rules_apple`: _v0.19.0_ -> _v0.20.0_
> Project: Update dependency versions

- Source/common/SNTConfigurator.h
- Source/common/SNTConfigurator.m
- Source/santad/EventProviders/SNTEndpointSecurityManager.mm
- version.bzl
> Add the option to ignore actions from other ES clients

- .github/workflows/ci.yml
This workflow will do a release build and run all tests on every pull request on to the main branch and every push to other branches. If a push _only_ affects docs the workflow won't run
> Project: Add GitHub Actions CI workflow

- Podfile.lock
- Santa.xcodeproj/project.pbxproj
- Source/santad/EventProviders/SNTEndpointSecurityManager.mm
* Also exclude self from IgnoreOtherEndpointSecurityClients debug logs
> project: update Xcode project to build universal binaries

- Source/common/SNTKernelCommon.h
- Source/santad/EventProviders/SNTEndpointSecurityManager.mm
- Source/santad/Logs/SNTSyslogEventLog.m
- Source/santad/SNTCompilerController.m
This pull request adds a single commit with code to track the pidversion of processes and log it along with other process information.
> Log pidversion along with pid.

- docs/development/contributing.md
- docs/index.md
> Docs: Fix some broken links in the index

- Source/santad/EventProviders/SNTCachingEndpointSecurityManager.mm
- Source/santad/EventProviders/SNTEndpointSecurityManager.mm
- version.bzl
Bump version to 2021.2
Fixes #532
> santad: Fix caching of deny decisions

- docs/details/santactl.md
> Docs: Fix more broken docs links

- README.md
Santa is hiring - add a link to the open role.
> Post a link to open roles on Santa

- Source/santad/EventProviders/SNTEndpointSecurityManager.mm
Missed handling the fallthrough from https://github.com/google/santa/pull/569.
This should've been caught by a linter, will add that to our CI in a followup PR
> Add an extra return on the rename case

- WORKSPACE
This removes a lot of warnings when starting in a clean workspace
> Project: Update deps in WORKSPACE to be reproducible.

- .gitignore
- docs/development/building.md
- santa.tulsiproj/Configs/Santa.tulsigen
- santa.tulsiproj/project.tulsiconf
Create a tulsi project that correctly labels and marks our main artifacts (all of our binaries and unit tests) and update the docs
> Add tulsi project

- README.md
This adds Rudolph to the list of sync services.
> Add Rudolph to list of sync servers

- Testing/integration/BUILD
- Testing/integration/SNTExecTest.m
- Testing/integration_tests.sh
- Testing/start_env.sh
All of the groundwork's there now for testing install -> sync -> running a binary
> Add regular execution integration tests

- .github/workflows/ci.yml
- BUILD
- Source/common/BUILD
- Source/common/SNTXPCMetricServiceInterface.m
- Source/santa/BUILD
- Source/santa_driver/BUILD
- Source/santactl/BUILD
- Source/santad/BUILD
- Testing/integration/BUILD
- Testing/lint.sh
- WORKSPACE
Also lint our files accordingly
> Add linter step with clang-format and buildifier.

- Source/santad/SNTApplicationCoreMetrics.m
- Source/santad/SNTApplicationCoreMetricsTest.m
This changes the default root label for hostname to match up with other systems.
> Fixed up typo related to hostname vs. host_name

- Source/santactl/Commands/SNTCommandStatus.m
Linked issue: https://github.com/google/santa/issues/657
> Add santametricservice information to $ santactl status

- docs/deployment/configuration.md
- docs/deployment/troubleshooting.md
- docs/details/logs.md
- docs/index.md
I split these out over 3 commits as you're welcome to nitpick and thought it may be easier to omit a changed file entirely, if I should squash feel free to let me know just the same
> EnableSysxCache docs, etc

- .gitignore
Update the `.gitignore` to ignore VS Code directories.
> Ignore VSCode directories

- Source/common/SNTConfigurator.h
- Source/common/SNTConfigurator.m
- Source/santasyncservice/SNTSyncManager.m
- docs/deployment/configuration.md
> Sync: Allow configuring proxies

- Source/santametricservice/Formats/SNTMetricMonarchJSONFormatTest.m
- Source/santametricservice/Formats/SNTMetricRawJSONFormatTest.m
- Source/santametricservice/SNTMetricServiceTest.m
- Testing/clang_analyzer/run_clang_analyzer.sh
Also fix warnings for unused variables. The other warnings are more
nontrivial & require some light refactoring to fix, and will come in a followup PR.
I'll add the actual results to our CI as well once these are all fixed.
> Add clang_analyzer report generation script

- Conf/Package/Distribution.xml
This should avoid prompts to install Rosetta when installing the .pkg.
Prompted by #732
> Project: Add arm64 to hostArchitectures for productbuild

- Conf/uninstall.sh
> Fix: uninstall.sh to remove the metric & bundle services.

- BUILD
- Source/common/BUILD
- Source/santad/BUILD
Modified target names to better match style of other projects
> Modified build target names for santa proto

- Source/santametricservice/Writers/BUILD
Simliar to https://github.com/google/santa/pull/781, but somehow I missed one file.
> Disable layering check for Objective-C

- Conf/Package/postinstall
- Conf/Package/preinstall
Thanks @bfreezy for notifying us about this issue!
> santasyncservice: handle loading and unloading of the service in the pkg

- Source/santad/EventProviders/SNTDeviceManager.mm
- Source/santad/EventProviders/SNTEndpointSecurityManager.mm
> santad: Copy/retain ES message for use in deadline handler.

- docs/.gitignore
- docs/Gemfile
This lets us test docs site changes by running `bundle exec jekyll serve` from inside the docs folder.
> Docs: Add gemfile for running jekyll locally.

- Source/common/SNTConfigurator.h
- Source/common/SNTConfigurator.m
- Source/common/SNTMetricSet.h
- Source/common/SNTMetricSet.m
- Source/common/SNTSyncConstants.h
- Source/common/SNTSyncConstants.m
- Source/common/SNTXPCControlInterface.h
- Source/santad/SNTDaemonControlController.m
- Source/santad/SNTExecutionController.m
- Source/santad/SNTExecutionControllerTest.m
- Source/santasyncservice/SNTSyncPreflight.m
- docs/deployment/configuration.md
> santad: Add DisableUnknownEventUpload option.

- docs/deployment/configuration.md
- docs/deployment/recommended-rollout-strategy.md
- docs/deployment/sync-servers.md
- docs/deployment/troubleshooting.md
Fixes #838 
Added a doc page with the recommended rollout strategy for deploying Santa.
> Docs: Add recommended rollout doc

- BUILD
- Source/santa/BUILD
- Source/santa/SNTNotificationManager.m
Also add a group for GUI unit_tests and include in the overall project tests group.
> GUI: Improve signing chain key reporting in distributed notifications.

- Source/santad/BUILD
- Source/santad/SNTDaemonControlController.mm
- Source/santad/SantadDeps.mm
> Build deps

- Source/santad/SNTExecutionControllerTest.mm
Fix non-void function/block does not return a value.
> Return a value from the test block

- Source/santad/BUILD
- Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/BUILD
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/binaryproto.proto
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool.cc
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool.h
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_log_batch_writer.cc
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_log_batch_writer.h
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_nowindows.cc
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_platform_specific.h
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_test.mm
- WORKSPACE
FSSpool and batch writers. Implements a modified maildir protocol.
This is stacked on top of the branch under review here: https://github.com/google/santa/pull/897
> Fsspool adopt

- Source/common/BUILD
- Source/common/santa_proto_include_wrapper.h
- Source/santad/BUILD
Workaround to layer proto header
> More import fixes

- Source/common/santa_proto_include_wrapper.h
- Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
- Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
Update include paths and add include guard
> Update include paths and add include guard

- docs/development/building.md
Update build docs to reflect new directory structure.
Fixes #910
> Update build docs. 

- Source/santad/Santad.mm
> Fix issue with transposed remount/banned block messages

- docs/known-limitations.md
Add documentation for the USB Mass Storage blocking features limitations.
> Update Known Limitations for USB Mass Storage Blocking

- Fuzzing/santad/src/checkCacheForVnodeID.mm
- Source/common/BUILD
- Source/common/SNTCachedDecision.h
- Source/common/SNTCachedDecision.mm
- Source/common/SNTCommon.h
- Source/common/SNTXPCUnprivilegedControlInterface.h
- Source/santactl/Commands/SNTCommandCheckCache.m
- Source/santad/EventProviders/AuthResultCache.h
- Source/santad/EventProviders/AuthResultCache.mm
- Source/santad/EventProviders/AuthResultCacheTest.mm
- Source/santad/SNTDaemonControlController.mm
- Source/santad/SNTExecutionController.mm
Also add factory method to create a `SantaVnode` from an `es_file_t`.
> Rename santa_vnode_id_t to SantaVnode

- Source/common/santa.proto
- Source/santad/BUILD
- Source/santad/Logs/EndpointSecurity/Logger.h
- Source/santad/Logs/EndpointSecurity/Logger.mm
- Source/santad/Logs/EndpointSecurity/LoggerTest.mm
- Source/santad/Logs/EndpointSecurity/MockLogger.h
- Source/santad/Logs/EndpointSecurity/Serializers/BasicString.h
- Source/santad/Logs/EndpointSecurity/Serializers/BasicString.mm
- Source/santad/Logs/EndpointSecurity/Serializers/BasicStringTest.mm
- Source/santad/Logs/EndpointSecurity/Serializers/Empty.h
- Source/santad/Logs/EndpointSecurity/Serializers/Empty.mm
- Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.h
- Source/santad/Logs/EndpointSecurity/Serializers/Protobuf.mm
- Source/santad/Logs/EndpointSecurity/Serializers/ProtobufTest.mm
- Source/santad/Logs/EndpointSecurity/Serializers/Serializer.h
- Source/santad/testdata/protobuf/v1/file_access.json
- Source/santad/testdata/protobuf/v2/file_access.json
- Source/santad/testdata/protobuf/v4/file_access.json
- Source/santad/testdata/protobuf/v5/file_access.json
- Source/santad/testdata/protobuf/v6/file_access.json
Also minor proto updates to the new file access event
> Serialize File Access events

- .github/workflows/e2e.yml
- .pylintrc
- Testing/integration/actions/start-vm.py
- Testing/integration/actions/start_vm.py
- Testing/lint.sh
Also adds pylint to the lint script to automatically catch this in the future.
> Lint the E2E start-vm Python script

- Source/santad/EventProviders/SNTEndpointSecurityClient.mm
- Source/santad/EventProviders/SNTEndpointSecurityClientBase.h
- Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
Fix issue where async processing wouldn't properly retain the message
> Fix message lifetime

- Source/santad/DataLayer/WatchItems.h
> Use absl_guarded_by instead of guarded_by

- LICENSE
Adds the MIT license to the repo-wide LICENSE file, specifically for VM code.
> Update LICENSE for VM code

- .allstar/binary_artifacts.yaml
> Allstar: Add fuzzing artifact

- .github/workflows/continuous.yml
- .github/workflows/fuzz.yml
Just realized these were wrong while checking on fuzzing last night, causing a lot more runs than intended.
> Fix nightly run cron specification

- Source/santad/DataLayer/WatchItemPolicy.h
- Source/santad/DataLayer/WatchItems.h
- Source/santad/DataLayer/WatchItems.mm
- Source/santad/DataLayer/WatchItemsTest.mm
- Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
- Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizerTest.mm
Also expanded on some negative test cases for all attributes
> Support configuring signing IDs for process exceptions

- Source/common/SNTConfigurator.m
> Configurator: Apply config updates in non-daemon processes

- Source/santad/BUILD
- Source/santad/EventProviders/EndpointSecurity/Message.h
- Source/santad/EventProviders/EndpointSecurity/Message.mm
- Source/santad/EventProviders/SNTEndpointSecurityClient.mm
- Source/santad/Logs/EndpointSecurity/Writers/File.h
- Source/santad/Logs/EndpointSecurity/Writers/File.mm
- Source/santad/Logs/EndpointSecurity/Writers/FileTest.mm
- Source/santad/Metrics.h
- Source/santad/Metrics.mm
- Source/santad/MetricsTest.mm
Took several CPU profiler traces. This branch addresses some decent wins that were low hanging fruit.
> Low hanging fruit perf changes

- Source/santad/DataLayer/WatchItems.mm
- Source/santad/DataLayer/WatchItemsTest.mm
Names must be legal C identifiers.
> Ensure watch item names conform to naming requirements

- .bazelrc
- .github/workflows/sanitizers.yml
Runs unit tests with asan, tsan, and ubsan in a separate workflow.
> Add new continuous test run with various sanitizers

- docs/deployment/sync-servers.md
Zentral has gained many more Santa-specific workflows since adding to this section in 2017. The updated description takes this into account.
> add updated description

- docs/_sass/custom/custom.scss
I have no idea what I'm doing.
> docs: fix width of sidebar on larger windows

- .bazelrc
- Source/common/PrefixTreeTest.mm
- Source/santactl/BUILD
- Source/santad/EventProviders/SNTEndpointSecurityAuthorizerTest.mm
- Source/santad/Logs/EndpointSecurity/Writers/FileTest.mm
These should clear up the last few TSAN failures. And good news, none of them are in real code - all just tests.
> Fix a couple last TSAN failures

- docs/deployment/file-access-auth.md
Also adds supported Santa version column.
> Document SigningID and PlatformBinary exception keys

- .github/workflows/sanitizers.yml
- Source/santad/EventProviders/SNTEndpointSecurityClientTest.mm
> One more TSAN fix

- Source/santactl/Commands/SNTCommandRule.m
> santactl/rule: Fix --path argument

- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_log_batch_writer.cc
- Source/santad/Logs/EndpointSecurity/Writers/FSSpool/fsspool_log_batch_writer.h
External port from cl/544046163
> Fix memleak in fsspool

- Source/common/SNTConfigurator.m
> Add kSyncEnableCleanSyncEventUpload to the _forcedConfigKeyTypes dict

- Source/gui/SNTNotificationManager.m
- Source/gui/SNTNotificationManagerTest.m
> Have distributed notifications delivered immediately

- docs/deployment/configuration.md
Document the SyncExtraHeaders configuration option added in #1144
> Document SyncExtraHeaders in configuration.md

- docs/deployment/troubleshooting.md
Found a minor typo while reviewing troubleshooting.md
> Fix typo in troubleshooting.md

- Source/santad/SNTExecutionControllerTest.mm
This PR adds a unit test for the fix in in #1165.
> Add Tests for #1165 Behavior.

- Source/common/BUILD
- Source/common/CertificateHelpers.h
- Source/common/CertificateHelpers.m
- Source/common/SNTBlockMessage.h
- Source/common/SNTBlockMessage.m
- Source/common/SNTConfigurator.h
- Source/common/SNTConfigurator.m
- Source/common/SNTFileAccessEvent.h
- Source/common/SNTFileAccessEvent.m
- Source/common/String.h
- Source/gui/BUILD
- Source/gui/SNTBinaryMessageWindowController.m
- Source/gui/SNTFileAccessMessageWindowController.h
- Source/gui/SNTFileAccessMessageWindowController.m
- Source/gui/SNTFileAccessMessageWindowView.swift
- Source/gui/SNTNotificationManager.m
- Source/santad/BUILD
- Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.h
- Source/santad/EventProviders/SNTEndpointSecurityFileAccessAuthorizer.mm
- Source/santad/SNTExecutionController.mm
- Source/santad/Santad.mm
- Source/santad/TTYWriter.h
- Source/santad/TTYWriter.mm
This PR adds UI and TTY messaging when access to a resource is blocked via the File Access Authorization feature.
#1084
> UI For Blocked File Access

- docs/deployment/configuration.md
Update configuration.md with details of the EnableDebugLogging configuration key.  Also some minor formatting changes.
> Update configuration.md to explain EnableDebugLogging

- Source/santactl/BUILD
- Source/santactl/Commands/SNTCommandFileInfo.m
> Additional build deps

- WORKSPACE
And other minor WORKSPACE fixups.
> Update to the latest hedron_compile_commands

- docs/development/sync-protocol.md
> chore: Fix typo s/occured/occurred/

- WORKSPACE
Pull in changes that will be used to address #1318
> Bump MOLCodesignChecker tag to latest

- README.md
Changed "and published" to "and are published"
> Slight Grammar fix in README

- docs/index.md
Changed a lot of grammar issues in the docs index.md
> More grammar fixes

- Source/common/BUILD
- Source/common/SNTBlockMessage.m
- Source/common/SNTBlockMessageTest.m
Also added a test to stop this from happening again
> GUI: Fix unicode rendering of attributed messages

- Source/santabundleservice/SNTBundleService.m
> Add cdhash, teamID, signingID to the bundle events

- Source/santactl/Commands/SNTCommandFileInfo.m
> fileinfo: cap the number of concurrent operations 

- Source/santasyncservice/SNTSyncStage.mm
> Allow empty data for 200 responses

- Source/common/SNTConfigurator.h
- Source/common/SNTConfigurator.m
- Source/gui/Resources/MessageWindow.xib
- Source/gui/SNTBinaryMessageWindowController.h
- Source/gui/SNTBinaryMessageWindowController.m
> GUI: Make dismiss button configurable, change default text back to dismiss

- Source/common/SNTMetricSet.m
> santad: Synchronize access to metric callback array
